### ISSUE TITLE
Products are missing from category pages / category view in adminhtml

### ISSUE THREAD

**Issue by nuwaus** [Smile-SA/elasticsuite#1149]
### Preconditions

Magento Version: 2.2.6

ElasticSuite Version : 2.6.1

Environment : Developer and production modes

Third party modules :

### Steps to reproduce

1. Having simple products in various categories with similar properties and values
2. Visiting the catalog pages / visiting categories section on adminhtml
3. Having identical settings for all products.

### Expected result

1. All the products must have visible on the frontend and backend and must be searchable.

### Actual result

1. Products which assigned to the category are showing on the table but not visible by Elastic
[
![screen shot 2018-10-24 at 3 29 15 pm](https://user-images.githubusercontent.com/209750/47424967-976f5900-d7a6-11e8-9eb7-f50b365abbab.png)
](url)

2. The same products are not searchable by SKU and not visible on frontend too
![screen shot 2018-10-24 at 4 03 51 pm](https://user-images.githubusercontent.com/209750/47424997-a6eea200-d7a6-11e8-9196-7ec16f703a43.png)

3. Only 2 products out of 4 are visible and the products which are not visible not searchable either.

**Comment by romainruaud** [comment]
@nuwaus 

What is the stock status of these missing products ? Are they in stock or out of stock ?

**Comment by nuwaus** [comment]
All the products are in stock status, enabled and manage stock is set to true as well. And all the products are having minimum 1 products in stock. Additionally as suggested in some other post having a similar issue 'status' attribute set to 'Yes' for use in the promotions field.

**Comment by romainruaud** [comment]
Kinda strange, are you able to look on the products in your Elasticsearch index ? If you are not familiar, you should be able to see them with something like : 

`curl -XGET localhost:9200/magento22ce_default_catalog_product*/_search?q=sku:XXXX`

where `magento22ce_default_catalog_product` correspond to the combination of : 
- alias defined in configuration (see here : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#indices-settings )
- the store code (in my dev env, its `default`).
- `catalog_product` is a constant string for the product index.

**Comment by romainruaud** [comment]
It seems to indicate that the product is not in the Elasticsearch Index.

Are you able to view the Elasticsearch server logs ? especially the `/var/log/elasticsearch/elasticsearch.log`

If you can access this file, try to set your indexers to `Update on Save` mode, and save this product via the back-office. If something is preventing the product being indexed into Elasticsearch, it should be shown in the log file.

**Comment by nuwaus** [comment]
I checked the error log, there are some errors

```
[2018-10-26T08:26:41,680][INFO ][o.e.c.m.MetaDataCreateIndexService] [o_i4TKV] [testmist_default_catalog_category_20181026_062641] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2018-10-26T08:26:41,862][INFO ][o.e.c.r.a.AllocationService] [o_i4TKV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[testmist_default_catalog_category_20181026_062641][0]] ...]).
[2018-10-26T08:26:41,962][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_category_20181026_062641/2t8BorGmQd6zd20hCvPOvw] create_mapping [category]
[2018-10-26T08:26:42,105][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_category_20181026_062641/2t8BorGmQd6zd20hCvPOvw] update_mapping [category]
[2018-10-26T08:26:42,387][INFO ][o.e.c.m.MetaDataUpdateSettingsService] [o_i4TKV] updating number_of_replicas to [0] for indices [testmist_default_catalog_category_20181026_062641]
[2018-10-26T08:26:42,405][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:26:42,405][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:26:42,417][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:26:42,417][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:26:42,609][INFO ][o.e.c.m.MetaDataDeleteIndexService] [o_i4TKV] [testmist_default_catalog_category_20180815_162606/7oyEVT78RTisxGxP1cChSA] deleting index
[2018-10-26T08:26:42,813][INFO ][o.e.c.m.MetaDataCreateIndexService] [o_i4TKV] [testmist_default_thesaurus_20181026_062642] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2018-10-26T08:26:42,984][INFO ][o.e.c.r.a.AllocationService] [o_i4TKV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[testmist_default_thesaurus_20181026_062642][0]] ...]).
[2018-10-26T08:26:43,203][INFO ][o.e.c.m.MetaDataDeleteIndexService] [o_i4TKV] [testmist_default_thesaurus_20180815_162709/PcWSw5ngRaO8soNL8ebi4g] deleting index
[2018-10-26T08:31:36,828][INFO ][o.e.c.m.MetaDataCreateIndexService] [o_i4TKV] [testmist_default_catalog_category_20181026_063136] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2018-10-26T08:31:36,985][INFO ][o.e.c.r.a.AllocationService] [o_i4TKV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[testmist_default_catalog_category_20181026_063136][0]] ...]).
[2018-10-26T08:31:37,086][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_category_20181026_063136/mjpUOdthSSquY1WFh9JGmg] create_mapping [category]
[2018-10-26T08:31:37,265][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_category_20181026_063136/mjpUOdthSSquY1WFh9JGmg] update_mapping [category]
[2018-10-26T08:31:37,574][INFO ][o.e.c.m.MetaDataUpdateSettingsService] [o_i4TKV] updating number_of_replicas to [0] for indices [testmist_default_catalog_category_20181026_063136]
[2018-10-26T08:31:37,599][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:31:37,599][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:31:37,616][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:31:37,616][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:31:37,819][INFO ][o.e.c.m.MetaDataDeleteIndexService] [o_i4TKV] [testmist_default_catalog_category_20181026_062641/2t8BorGmQd6zd20hCvPOvw] deleting index
[2018-10-26T08:31:38,018][INFO ][o.e.c.m.MetaDataCreateIndexService] [o_i4TKV] [testmist_default_thesaurus_20181026_063138] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2018-10-26T08:31:38,185][INFO ][o.e.c.r.a.AllocationService] [o_i4TKV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[testmist_default_thesaurus_20181026_063138][0]] ...]).
[2018-10-26T08:31:38,409][INFO ][o.e.c.m.MetaDataDeleteIndexService] [o_i4TKV] [testmist_default_thesaurus_20181026_062642/BxdwMQRpS5GxWTOKgCrjQw] deleting index
[2018-10-26T08:34:51,328][INFO ][o.e.c.m.MetaDataCreateIndexService] [o_i4TKV] [testmist_default_catalog_product_20181026_063451] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2018-10-26T08:34:51,492][INFO ][o.e.c.r.a.AllocationService] [o_i4TKV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[testmist_default_catalog_product_20181026_063451][0]] ...]).
[2018-10-26T08:34:51,596][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_product_20181026_063451/7NCBr0z9Q22raGYrWcHVgA] create_mapping [product]
[2018-10-26T08:35:26,530][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_product_20181026_063451/7NCBr0z9Q22raGYrWcHVgA] update_mapping [product]
[2018-10-26T08:36:41,926][DEBUG][o.e.a.b.TransportShardBulkAction] [o_i4TKV] [testmist_default_catalog_product_20181026_063451][0] failed to execute bulk item (index) BulkShardRequest [[testmist_default_catalog_product_20181026_063451][0]] containing [1000] requests
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [pa_klepelaantal]

	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:298) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:468) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:591) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:580) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:526) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:385) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:373) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:66) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:277) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:530) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:507) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.prepareIndexOperationOnPrimary(TransportShardBulkAction.java:458) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:466) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:145) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:114) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:975) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:944) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:345) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:270) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:921) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:151) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1659) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:933) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:92) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:291) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:266) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:248) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.10.jar:5.6.10]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NumberFormatException: For input string: "24 &amp; 48"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:?]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_161]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.doubleValue(AbstractXContentParser.java:225) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$3.parse(NumberFieldMapper.java:377) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$3.parse(NumberFieldMapper.java:369) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:1072) ~[elasticsearch-5.6.10.jar:5.6.10]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:287) ~[elasticsearch-5.6.10.jar:5.6.10]
	... 38 more
[2018-10-26T08:42:10,368][INFO ][o.e.c.m.MetaDataUpdateSettingsService] [o_i4TKV] updating number_of_replicas to [0] for indices [testmist_default_catalog_product_20181026_063451]
[2018-10-26T08:42:10,387][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:42:10,387][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:42:10,401][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:42:10,401][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:42:14,515][INFO ][o.e.c.m.MetaDataCreateIndexService] [o_i4TKV] [testmist_default_catalog_category_20181026_064214] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2018-10-26T08:42:14,682][INFO ][o.e.c.r.a.AllocationService] [o_i4TKV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[testmist_default_catalog_category_20181026_064214][0]] ...]).
[2018-10-26T08:42:14,778][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_category_20181026_064214/XJiTw6xRTWOJuh3sCU7RIA] create_mapping [category]
[2018-10-26T08:42:14,923][INFO ][o.e.c.m.MetaDataMappingService] [o_i4TKV] [testmist_default_catalog_category_20181026_064214/XJiTw6xRTWOJuh3sCU7RIA] update_mapping [category]
[2018-10-26T08:42:15,246][INFO ][o.e.c.m.MetaDataUpdateSettingsService] [o_i4TKV] updating number_of_replicas to [0] for indices [testmist_default_catalog_category_20181026_064214]
[2018-10-26T08:42:15,274][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:42:15,274][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:42:15,287][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.translog.durability] from [async] to [request]
[2018-10-26T08:42:15,288][INFO ][o.e.c.s.IndexScopedSettings] [o_i4TKV] updating [index.refresh_interval] from [30s] to [1s]
[2018-10-26T08:42:15,487][INFO ][o.e.c.m.MetaDataDeleteIndexService] [o_i4TKV] [testmist_default_catalog_category_20181026_063136/mjpUOdthSSquY1WFh9JGmg] deleting index
[2018-10-26T08:42:15,640][INFO ][o.e.c.m.MetaDataCreateIndexService] [o_i4TKV] [testmist_default_thesaurus_20181026_064215] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2018-10-26T08:42:15,799][INFO ][o.e.c.r.a.AllocationService] [o_i4TKV] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[testmist_default_thesaurus_20181026_064215][0]] ...]).
[2018-10-26T08:42:16,005][INFO ][o.e.c.m.MetaDataDeleteIndexService] [o_i4TKV] [testmist_default_thesaurus_20181026_063138/f1hHTH0eQ0CGOOxumhEP0Q] deleting index

```

here, the 

> pa_klepelaantal

is an custom attribute in our store, and there are more similar errors for few other similar attributes, i trimmed down the similar error because log is too big, it seems like it having a hard time parsing custom attributes?

**Comment by romainruaud** [comment]
Yep, from what I can see, there is an attribute which is expected by Elasticsearch to be a decimal/number, but which contains "24 &amp; 48".

It causes Elasticsearch to reject the whole document : so the product is missing inside Elasticsearch.

You are probably having a data issue : if Elasticsuite is treating your attribute as a decimal/number, it's because this attribute is evaluated as being a number/string by this piece of code : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php#L112

Can you check the mapping of your index ? You should be able to obtain it via : 

`curl -XGET localhost:9200/magento22ce_default_catalog_product*/_mapping?pretty`

Let me know what is shown for this problematic field, so we'll be able to ensure how it's defined in the mapping. Please give also the content of the `eav_attribute` table for this attribute.

But you'll probably have to fix either the input data (but I assume you want to keep the "&amp;" inside the values), or the attribute definition, which should probably be switched to a `varchar` if the values it contains are strings and not number/decimal values.

Regards

**Comment by nuwaus** [comment]
Thank you for the fast response, I executed the given command and this is the result of it,

`{
  "magrixpe_default_catalog_product_20181023_205535" : {
    "mappings" : {
      "product" : {
        "_all" : {
          "enabled" : false
        },
        "properties" : {
          "attribute_set_id" : {
            "type" : "integer"
          },
          "autocomplete" : {
            "type" : "text",
            "fields" : {
              "shingle" : {
                "type" : "text",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "text",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "category" : {
            "type" : "nested",
            "properties" : {
              "category_id" : {
                "type" : "integer"
              },
              "is_blacklisted" : {
                "type" : "boolean"
              },
              "is_parent" : {
                "type" : "boolean"
              },
              "is_virtual" : {
                "type" : "boolean"
              },
              "name" : {
                "type" : "text",
                "copy_to" : [
                  "search",
                  "spelling"
                ],
                "analyzer" : "standard"
              },
              "position" : {
                "type" : "integer"
              }
            }
          },
          "children_ids" : {
            "type" : "integer"
          },
          "color" : {
            "type" : "integer"
          },
          "configurable_attributes" : {
            "type" : "keyword"
          },
          "created_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "description" : {
            "type" : "text",
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "standard"
          },
          "entity_id" : {
            "type" : "integer"
          },
          "has_options" : {
            "type" : "boolean"
          },
          "image" : {
            "type" : "keyword"
          },
          "indexed_attributes" : {
            "type" : "keyword"
          },
          "manufacturer" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "text",
            "fields" : {
              "sortable" : {
                "type" : "text",
                "analyzer" : "sortable",
                "fielddata" : true
              }
            },
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "standard"
          },
          "option_text_color" : {
            "type" : "text",
            "fields" : {
              "untouched" : {
                "type" : "keyword"
              }
            },
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "standard"
          },
          "option_text_manufacturer" : {
            "type" : "text",
            "fields" : {
              "untouched" : {
                "type" : "keyword"
              }
            },
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "standard"
          },
          "option_text_status" : {
            "type" : "text",
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "standard"
          },
          "option_text_tax_class_id" : {
            "type" : "text",
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "standard"
          },
          "pa_drukkracht" : {
            "type" : "double"
          },
          "pa_klepelaantal" : {
            "type" : "double"
          },
          "pa_kloofslag" : {
            "type" : "double"
          },
          "pa_koppel" : {
            "type" : "double"
          },
          "pa_minpk" : {
            "type" : "double"
          },
          "pa_snelheid" : {
            "type" : "double"
          },
          "pa_snijhoogte" : {
            "type" : "double"
          },
          "pa_tractor_power_hp" : {
            "type" : "double"
          },
          "pa_werkbreedte" : {
            "type" : "keyword"
          },
          "price" : {
            "type" : "nested",
            "properties" : {
              "customer_group_id" : {
                "type" : "integer"
              },
              "is_discount" : {
                "type" : "boolean"
              },
              "original_price" : {
                "type" : "double"
              },
              "price" : {
                "type" : "double"
              }
            }
          },
          "required_options" : {
            "type" : "boolean"
          },
          "search" : {
            "type" : "text",
            "fields" : {
              "shingle" : {
                "type" : "text",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "text",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "search_query" : {
            "type" : "nested",
            "properties" : {
              "is_blacklisted" : {
                "type" : "boolean"
              },
              "position" : {
                "type" : "integer"
              },
              "query_id" : {
                "type" : "integer"
              }
            }
          },
          "search_weight" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "short_description" : {
            "type" : "text",
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "standard"
          },
          "sku" : {
            "type" : "text",
            "fields" : {
              "sortable" : {
                "type" : "text",
                "analyzer" : "sortable",
                "fielddata" : true
              },
              "untouched" : {
                "type" : "keyword"
              }
            },
            "copy_to" : [
              "search",
              "spelling"
            ],
            "analyzer" : "reference"
          },
          "spelling" : {
            "type" : "text",
            "fields" : {
              "phonetic" : {
                "type" : "text",
                "analyzer" : "phonetic"
              },
              "shingle" : {
                "type" : "text",
                "analyzer" : "shingle"
              },
              "whitespace" : {
                "type" : "text",
                "analyzer" : "whitespace"
              }
            },
            "analyzer" : "standard"
          },
          "status" : {
            "type" : "integer"
          },
          "stock" : {
            "properties" : {
              "is_in_stock" : {
                "type" : "boolean"
              },
              "qty" : {
                "type" : "integer"
              }
            }
          },
          "tax_class_id" : {
            "type" : "integer"
          },
          "type_id" : {
            "type" : "keyword"
          },
          "updated_at" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
          },
          "visibility" : {
            "type" : "integer"
          }
        }
      }
    }
  }
}`

Thanks!

**Comment by romainruaud** [comment]
Yes, `pa_klepelaantal` is a backend varchar, but has the `validate-number` frontend_class, so it falls in this case : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php#L122

That's why it's shown as a `double` in your mapping : 

```
					"pa_klepelaantal": {
						"type": "double"
					},
```

So probably it's a mistake to have `validate-number` on this field, especially if values are containing string, because Magento may prevent you from contributing such string values in the back-office.

Regards
