### ISSUE TITLE
Can not install Elasticsuite 2.7.0

### ISSUE THREAD

**Issue by minhluan259** [Smile-SA/elasticsuite#1222]
Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface

### Preconditions

PHP 7.1.24, Elasticsearch 6.5

Magento Version : 2.3.0 CE

ElasticSuite Version : 2.7.0

Environment : Production

Third party modules : none

### Steps to reproduce

After require and add config Elasticsuite follow wiki document
run command `bin/magento setup:upgrade`

### Expected result

1. Install Elasticsuite without error

### Actual result

1. [Screenshot, logs]
```
Module 'Magento_WishlistAnalytics':
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface in /var/www/clients/client0/web6/web/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /var/www/clients/client0/web6/web/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...')
#1 /var/www/clients/client0/web6/web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...')
#2 /var/www/clients/client0/web6/web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'stockResolver', 'Smile\\Elasticsu...')
#3 /var/www/clients/client0/web6/web/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resol in /var/www/clients/client0/web6/web/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```

**Comment by Swahjak** [comment]
This seems to be related to your installation. `Magento\InventorySalesApi\Api\StockResolverInterface` should be available in `vendor/magento/module-inventory-sales-api/Api/StockResolverInterface.php` on a Magento 2.3 installation (and mapped in `vendor/magento/module-inventory-sales/etc/di.xml` to `<preference for="Magento\InventorySalesApi\Api\StockResolverInterface" type="Magento\InventorySales\Model\StockResolver"/>`. 

We've had the same 'issue' but it was due to the fact that we had removed the magento/module-inventory-sales-api using composer replace. Maybe there is something there. Could also be related to the generated folder or old cache.

**Comment by rbayet** [comment]
Re-opening the issue as in the course of the dev, an additional module was created with correct extra dependencies.
Those extra dependencies were **not** reported to Smile_ElasticsuiteCatalog when the additional module was dropped.

**Comment by rbayet** [comment]
Fixed by PR #1229 in release 2.7.1

**Comment by Yamaha32088** [comment]
@rbayet I am having the same problem even after installing the 2.7.1 version of ElasticSuite.

```[Fri Dec 14 22:27:34.700980 2018] [php7:error] [pid 3480] [client xxxxxxxx:58503] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\\InventorySalesApi\\Api\\StockResolverInterface in /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116\nStack trace:\n#0 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Invento...', Array)\n#1 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Invento...')\n#2 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Invento...')\n#3 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Smile\\\\Elasticsu...')\n#4 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Sm in /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116
[Fri Dec 14 22:27:37.192325 2018] [php7:error] [pid 3431] [client xxxxxxx:58508] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\\InventorySalesApi\\Api\\StockResolverInterface in /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116\nStack trace:\n#0 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Invento...', Array)\n#1 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Invento...')\n#2 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Invento...')\n#3 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Smile\\\\Elasticsu...')\n#4 /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Sm in /var/www/devsite/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116
```

**Comment by Swahjak** [comment]
https://github.com/Smile-SA/elasticsuite/blob/2.7.1/composer.json#L33

Are you running with `MAGE_MODE=production`?  Because you are running through `vendor/magento/framework/ObjectManager/Factory/Compiled.php(108)` which would suggest you have compiled Magento using `bin/magento setup:compile`.

**Comment by Yamaha32088** [comment]
@Swahjak yes it is running in production mode and I do run `bin/magento setup:compile`

**Comment by husseycoding** [comment]
Seeing this issue with Magento 2.3 and module version 2.7.2.  Worth noting that this is actually an issue with reindexing, it shows during installation as data setup runs a reindex.

**Comment by andykim** [comment]
I upgrade to Magento 2.3 and install elasticsuite v2.7.2 and when i run php bin/magento setup:upgrade

Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\InventorySalesApi\Api\StockResolverInterface in /hdd/www/v2.gsmpartscenter.com/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /hdd/www/v2.gsmpartscenter.com/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...')
#1 /hdd/www/v2.gsmpartscenter.com/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...')
#2 /hdd/www/v2.gsmpartscenter.com/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'stockResolver', 'Smile\\Elasticsu...')
#3 /hdd/www/v2.gsmpartscenter.com/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRu in /hdd/www/v2.gsmpartscenter.com/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
![screenshot from 2018-12-30 07-39-43](https://user-images.githubusercontent.com/5335952/50543278-2e70eb00-0c06-11e9-8a88-378a757ebda3.png)

**Comment by hectorrojas4** [comment]
If the class `Magento\InventorySalesApi\Api\StockResolverInterface` can not be instantiated, it is possible that the module is disabled in `app/etc/config.php` file. Make sure that the Inventory modules are enabled:

```
<?php
return [
    'modules' => [
        ...
        'Magento_Inventory' => 1,
        'Magento_InventoryAdminUi' => 1,
        'Magento_InventoryApi' => 1,
        'Magento_InventoryBundleProduct' => 1,
        'Magento_InventoryBundleProductAdminUi' => 1,
        'Magento_InventoryCatalog' => 1,
        'Magento_InventorySales' => 1,
        'Magento_InventoryCatalogAdminUi' => 1,
        'Magento_InventoryCatalogApi' => 1,
        'Magento_InventoryCatalogSearch' => 1,
        'Magento_InventoryConfigurableProduct' => 1,
        'Magento_InventoryConfigurableProductAdminUi' => 1,
        'Magento_InventoryConfigurableProductIndexer' => 1,
        'Magento_InventoryConfiguration' => 1,
        'Magento_InventoryConfigurationApi' => 1,
        'Magento_InventoryGroupedProduct' => 1,
        'Magento_InventoryGroupedProductAdminUi' => 1,
        'Magento_InventoryGroupedProductIndexer' => 1,
        'Magento_InventoryImportExport' => 1,
        'Magento_InventoryIndexer' => 1,
        'Magento_InventoryLowQuantityNotification' => 1,
        'Magento_InventoryLowQuantityNotificationAdminUi' => 1,
        'Magento_InventoryLowQuantityNotificationApi' => 1,
        'Magento_InventoryMultiDimensionalIndexerApi' => 1,
        'Magento_InventoryProductAlert' => 1,
        'Magento_InventoryReservations' => 1,
        'Magento_InventoryReservationsApi' => 1,
        'Magento_InventoryCache' => 1,
        'Magento_InventorySalesAdminUi' => 1,
        'Magento_InventorySalesApi' => 1,
        'Magento_InventorySalesFrontendUi' => 1,
        'Magento_InventoryShipping' => 1,
        'Magento_InventorySourceDeductionApi' => 1,
        'Magento_InventorySourceSelection' => 1,
        'Magento_InventorySourceSelectionApi' => 1,
        ...
    ]
];
```

**Comment by minhluan259** [comment]
I found the cause of the problem because upgraded magento 2.2 to magento 2.3 incorrectly.
Follow this guild 
https://devdocs.magento.com/guides/v2.3/release-notes/backward-incompatible-changes/index.html 
to resolved the issue.
Hope this can help.

**Comment by frostblogNet** [comment]
Hello @minhluan259 

I have followed this guide but I ran into the same problem. Can you tell me want exactly was the solution.

Thanks in advance
Jens

**Comment by paalsoberg** [comment]
What about if you don't want the inventory / MSI modules installed?

**Comment by Swahjak** [comment]
@paalsoberg  There has been some discussion about that in https://github.com/Smile-SA/elasticsuite/issues/1517

**Comment by rbayet** [comment]
Hello @paalsoberg, 

2.7.7 and 2.8.0 releases introduced a fix that should allow you to use either the MSI modules or the legacy cataloginventory module.
Unless you're using **PHP 7.3** which does not like [a particular return type annotation](#1600) : this is to be addressed in our (very soon) incoming 2.8.3 release.

Regards,

**Comment by Swahjak** [comment]
@rbayet Will this still require installation (with composer) of the msi modules?

**Comment by rbayet** [comment]
@Swahjak Yes, the MSI modules `magento/module-inventory-sales-api`, `magento/module-inventory-sales` and `magento/module-inventory-indexer` are still present in our `composer.json` so those will be required at install.

They are also present in `smile/module-elasticsuite-catalog`'s module.xml file **but** you can disable them. 
Well them and the modules they are required for or simply ALL the MSI modules in one go with (on a CE 2.3.3) : 
`php bin/magento module:disable Magento_Inventory Magento_InventoryAdminUi Magento_InventoryAdvancedCheckout Magento_InventoryApi Magento_InventoryBundleProduct Magento_InventoryBundleProductAdminUi Magento_InventoryCatalog Magento_InventorySales Magento_InventoryCatalogAdminUi Magento_InventoryCatalogApi Magento_InventoryCatalogSearch Magento_InventoryConfigurableProduct Magento_InventoryConfigurableProductAdminUi Magento_InventoryConfigurableProductIndexer Magento_InventoryConfiguration Magento_InventoryConfigurationApi Magento_InventoryDistanceBasedSourceSelection Magento_InventoryDistanceBasedSourceSelectionAdminUi Magento_InventoryDistanceBasedSourceSelectionApi Magento_InventoryElasticsearch Magento_InventoryExportStockApi Magento_InventoryIndexer Magento_InventorySalesApi Magento_InventoryGroupedProduct Magento_InventoryGroupedProductAdminUi Magento_InventoryGroupedProductIndexer Magento_InventoryImportExport Magento_InventoryCache Magento_InventoryLowQuantityNotification Magento_InventoryLowQuantityNotificationAdminUi Magento_InventoryLowQuantityNotificationApi Magento_InventoryMultiDimensionalIndexerApi Magento_InventoryProductAlert Magento_InventoryRequisitionList Magento_InventoryReservations Magento_InventoryReservationCli Magento_InventoryReservationsApi Magento_InventoryExportStock Magento_InventorySalesAdminUi Magento_InventorySalesFrontendUi Magento_InventorySetupFixtureGenerator Magento_InventoryShipping Magento_InventorySourceDeductionApi Magento_InventorySourceSelection Magento_InventorySourceSelectionApi Magento_InventoryShippingAdminUi Magento_InventoryGraphQl`
and have your instance still working correctly.

The same way Magento_LayeredNavigationStaging is referenced in `smile/module-elasticsuite-catalog` module.xml without issue on CE/Open Source versions of M2 where this module simply does not exist.

Regards

**Comment by SolsWebdesign** [comment]
We really have no need for MultiStock and to keep the shop lean and fast we have disabled (and completely removed) MultiStock and we are running into compilation errors:
[ReflectionException]
  Class Magento\InventorySalesApi\Api\StockResolverInterface does not exist
It would really be nice if this can be changed so removing the modules will not cause these errors.

**Comment by romainruaud** [comment]
@SolsWebdesign please don't publish messages in closed issues but open a new one instead if you have issue.

That being said, you should not "remove completely" MSI. You just have to disable all `Magento_InventoryXXX` modules but keep them installed.

And of course, you have to use at least ElasticSuite >2.7.7.

Regards

**Comment by rbayet** [comment]
@SolsWebdesign for the sake of clarity, please open a specific issue, stating the versions of M2 and Elasticsuite you are using, considering, as shown in my [previous comment above](https://github.com/Smile-SA/elasticsuite/issues/1222#issuecomment-550414316) and the following, there should not be any problem remaining.
It that is still the case, we'll investigate.

Regards,

**Comment by peterjaap** [comment]
@SolsWebdesign @paalsoberg 

Here's a patch I made to make Elasticsuite work without any MSI modules actually *installed* (so removed with the composer replace trick). Formatted for use with [vaimo/composer-patches](https://github.com/vaimo/composer-patches).

```
Removed dependency on MSI modules

@package smile/elasticsuite
@link https://github.com/Smile-SA/elasticsuite/issues/1222

diff --git src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php
index ca4557d..f07e059 100644
--- src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php
+++ src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php
@@ -14,7 +14,6 @@
 namespace Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource;

 use Smile\ElasticsuiteCore\Api\Index\DatasourceInterface;
-use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryDataInterface;
 use \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\Deprecation\InventoryData as Deprecation;

 /**
@@ -27,7 +26,7 @@ use \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Data
 class InventoryData implements DatasourceInterface
 {
     /**
-     * @var InventoryDataInterface
+     * @var Deprecation
      */
     private $resourceModel;

@@ -75,31 +74,15 @@ class InventoryData implements DatasourceInterface
     }

     /**
-     * Init proper resource model.
-     *
-     * Should be default implementation of InventoryDataInterface if MSI modules are enabled.
-     *
-     * Otherwise we fallback to old-style CatalogInventory indexing.
      *
      * @deprecated To be removed with Magento 2.4 and the dismantlement of legacy CatalogInventory module.
      *
-     * @return InventoryDataInterface
+     * @return Deprecation
      */
     private function getResourceModel()
     {
         if ($this->resourceModel === null) {
-            $resourceName = InventoryDataInterface::class;
-
-            try {
-                // Will try to fetch default implementation and fail in case of missing MSI modules or dependencies.
-                $stockResolver = $this->config->getPreference(\Magento\InventorySalesApi\Api\StockResolverInterface::class);
-                if (ltrim($stockResolver, '\\') === ltrim(\Magento\InventorySalesApi\Api\StockResolverInterface::class, '\\')) {
-                    $resourceName = Deprecation::class;
-                }
-            } catch (\Exception $exception) {
-                ; // Nothing to do, it's already kinda hacky to allow this deprecation fallback to happen.
-            }
-
+            $resourceName = Deprecation::class;
             $this->resourceModel = $this->objectManager->get($resourceName);
         }

diff --git src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php
deleted file mode 100644
index 5ee7d1e..0000000
--- src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php
+++ /dev/null
@@ -1,134 +0,0 @@
-<?php
-/**
- * DISCLAIMER
- *
- * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
- * versions in the future.
- *
- * @category  Smile
- * @package   Smile\ElasticsuiteCatalog
- * @author    Romain Ruaud <romain.ruaud@smile.fr>
- * @copyright 2020 Smile
- * @license   Open Software License ("OSL") v. 3.0
- */
-namespace Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource;
-
-use Smile\ElasticsuiteCatalog\Model\ResourceModel\Eav\Indexer\Indexer;
-use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryDataInterface;
-use Magento\Framework\App\ResourceConnection;
-use Magento\Framework\EntityManager\MetadataPool;
-use Magento\Store\Model\StoreManagerInterface;
-use Magento\InventorySalesApi\Api\Data\SalesChannelInterface;
-use Magento\InventorySalesApi\Api\StockResolverInterface;
-use Magento\InventoryIndexer\Model\StockIndexTableNameResolverInterface;
-use Magento\InventoryIndexer\Indexer\IndexStructure;
-
-/**
- * Multi Source Inventory Catalog Inventory Data source resource model
- *
- * @category Smile
- * @package  Smile\ElasticsuiteCatalog
- * @author   Romain Ruaud <romain.ruaud@smile.fr>
- */
-class InventoryData extends Indexer implements InventoryDataInterface
-{
-    /**
-     * @var StockResolverInterface
-     */
-    private $stockResolver;
-
-    /**
-     * @var StockIndexTableNameResolverInterface
-     */
-    private $stockIndexTableProvider;
-
-    /**
-     * @var int[]
-     */
-    private $stockIdByWebsite = [];
-
-    /**
-     * InventoryData constructor.
-     *
-     * @param ResourceConnection                   $resource                Database adapter.
-     * @param StoreManagerInterface                $storeManager            Store manager.
-     * @param MetadataPool                         $metadataPool            Metadata Pool
-     * @param StockResolverInterface               $stockResolver           Stock resolver.
-     * @param StockIndexTableNameResolverInterface $stockIndexTableProvider Stock index table provider.
-     */
-    public function __construct(
-        ResourceConnection $resource,
-        StoreManagerInterface $storeManager,
-        MetadataPool $metadataPool,
-        StockResolverInterface $stockResolver,
-        StockIndexTableNameResolverInterface $stockIndexTableProvider
-    ) {
-        $this->stockResolver = $stockResolver;
-        $this->stockIndexTableProvider = $stockIndexTableProvider;
-
-        parent::__construct($resource, $storeManager, $metadataPool);
-    }
-
-    /**
-     * Load inventory data for a list of product ids and a given store.
-     * Expected rows structure : ['product_id', 'stock_status', 'qty'].
-     *
-     * @param integer $storeId    Store id.
-     * @param array   $productIds Product ids list.
-     *
-     * @return array
-     */
-    public function loadInventoryData($storeId, $productIds)
-    {
-        $websiteId = $this->getWebsiteId($storeId);
-        $stockId   = $this->getStockId($websiteId);
-        $tableName = $this->stockIndexTableProvider->execute($stockId);
-
-        $select = $this->getConnection()->select()
-            ->from(['product' => $this->getTable('catalog_product_entity')], [])
-            ->join(
-                ['stock_index' => $tableName],
-                'product.sku = stock_index.' . IndexStructure::SKU,
-                [
-                    'product_id'    => 'product.entity_id',
-                    'stock_status'  => 'stock_index.' . IndexStructure::IS_SALABLE,
-                    'qty'           => 'stock_index.' . IndexStructure::QUANTITY,
-                ]
-            )
-            ->where('product.entity_id IN (?)', $productIds)
-            ->group('product.entity_id');
-
-        return $this->getConnection()->fetchAll($select);
-    }
-
-    /**
-     * Retrieve stock_id by website
-     *
-     * @param int $websiteId The website Id
-     *
-     * @return int
-     */
-    private function getStockId($websiteId)
-    {
-        if (!isset($this->stockIdByWebsite[$websiteId])) {
-            $websiteCode = $this->storeManager->getWebsite($websiteId)->getCode();
-            $stock = $this->stockResolver->execute(SalesChannelInterface::TYPE_WEBSITE, $websiteCode);
-            $stockId = (int) $stock->getStockId();
-            $this->stockIdByWebsite[$websiteId] = $stockId;
-        }
-
-        return $this->stockIdByWebsite[$websiteId];
-    }
-
-    /**
-     * Retrieve Website Id by Store Id
-     *
-     * @param int $storeId The store id
-     *
-     * @return int
-     */
-    private function getWebsiteId($storeId)
-    {
-        return $this->storeManager->getStore($storeId)->getWebsiteId();
-    }
-}
diff --git src/module-elasticsuite-catalog/etc/di.xml src/module-elasticsuite-catalog/etc/di.xml
index 8121b1d..67d6ff0 100644
--- src/module-elasticsuite-catalog/etc/di.xml
+++ src/module-elasticsuite-catalog/etc/di.xml
@@ -275,9 +275,6 @@
         </arguments>
     </type>

-    <preference for="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryDataInterface"
-                type="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryData" />
-
     <virtualType name="Smile\ElasticsuiteCatalog\Search\Request\Product\Coverage\Builder"
         type="\Smile\ElasticsuiteCore\Search\Request\Builder">
         <arguments>
```

**Comment by peterjaap** [comment]
Updated patch for version 2.11.13;

```
@package smile/elasticsuite
@link https://github.com/Smile-SA/elasticsuite/issues/1222
@level 0

From 2e7a3782ecd5551439efc605c4990741582633bb Mon Sep 17 00:00:00 2001
From: peterjaap <peterjaap@elgentos.nl>
Date: Fri, 25 Apr 2025 08:46:12 +0200
Subject: [PATCH] Removed dependency on MSI modules - patch for version 2.11.13


diff --git src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php
index ca4557d..f07e059 100644
--- src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php
+++ src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php
@@ -14,7 +14,6 @@
 namespace Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource;
 
 use Smile\ElasticsuiteCore\Api\Index\DatasourceInterface;
-use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryDataInterface;
 use \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\Deprecation\InventoryData as Deprecation;
 
 /**
@@ -27,7 +26,7 @@ use \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Data
 class InventoryData implements DatasourceInterface
 {
     /**
-     * @var InventoryDataInterface
+     * @var Deprecation
      */
     private $resourceModel;
 
@@ -75,31 +74,15 @@ class InventoryData implements DatasourceInterface
     }
 
     /**
-     * Init proper resource model.
-     *
-     * Should be default implementation of InventoryDataInterface if MSI modules are enabled.
-     *
-     * Otherwise we fallback to old-style CatalogInventory indexing.
      *
      * @deprecated To be removed with Magento 2.4 and the dismantlement of legacy CatalogInventory module.
      *
-     * @return InventoryDataInterface
+     * @return Deprecation
      */
     private function getResourceModel()
     {
         if ($this->resourceModel === null) {
-            $resourceName = InventoryDataInterface::class;
-
-            try {
-                // Will try to fetch default implementation and fail in case of missing MSI modules or dependencies.
-                $stockResolver = $this->config->getPreference(\Magento\InventorySalesApi\Api\StockResolverInterface::class);
-                if (ltrim($stockResolver, '\\') === ltrim(\Magento\InventorySalesApi\Api\StockResolverInterface::class, '\\')) {
-                    $resourceName = Deprecation::class;
-                }
-            } catch (\Exception $exception) {
-                ; // Nothing to do, it's already kinda hacky to allow this deprecation fallback to happen.
-            }
-
+            $resourceName = Deprecation::class;
             $this->resourceModel = $this->objectManager->get($resourceName);
         }
 
diff --git src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php
deleted file mode 100644
index 0eb5b84..0000000
--- src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/InventoryData.php
+++ /dev/null
@@ -1,183 +0,0 @@
-<?php
-/**
- * DISCLAIMER
- *
- * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
- * versions in the future.
- *
- * @category  Smile
- * @package   Smile\ElasticsuiteCatalog
- * @author    Romain Ruaud <romain.ruaud@smile.fr>
- * @copyright 2020 Smile
- * @license   Open Software License ("OSL") v. 3.0
- */
-namespace Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource;
-
-use Magento\Framework\ObjectManagerInterface;
-use Smile\ElasticsuiteCatalog\Model\ResourceModel\Eav\Indexer\Indexer;
-use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryDataInterface;
-use Magento\Framework\App\ResourceConnection;
-use Magento\Framework\EntityManager\MetadataPool;
-use Magento\Store\Model\StoreManagerInterface;
-
-/**
- * Multi Source Inventory Catalog Inventory Data source resource model
- *
- * @category Smile
- * @package  Smile\ElasticsuiteCatalog
- * @author   Romain Ruaud <romain.ruaud@smile.fr>
- */
-class InventoryData extends Indexer implements InventoryDataInterface
-{
-    /**
-     * @var \Magento\InventorySalesApi\Api\StockResolverInterface
-     */
-    private $stockResolver;
-
-    /**
-     * @var \Magento\InventoryIndexer\Model\StockIndexTableNameResolverInterface
-     */
-    private $stockIndexTableProvider;
-
-    /**
-     * @var int[]
-     */
-    private $stockIdByWebsite = [];
-
-    /**
-     * @var \Magento\Framework\ObjectManagerInterface
-     */
-    private $objectManager;
-
-    /**
-     * InventoryData constructor.
-     *
-     * @param ResourceConnection     $resource      Database adapter.
-     * @param StoreManagerInterface  $storeManager  Store manager.
-     * @param MetadataPool           $metadataPool  Metadata Pool
-     * @param ObjectManagerInterface $objectManager Object Manager.
-     */
-    public function __construct(
-        ResourceConnection $resource,
-        StoreManagerInterface $storeManager,
-        MetadataPool $metadataPool,
-        ObjectManagerInterface $objectManager
-    ) {
-        $this->objectManager = $objectManager;
-
-        parent::__construct($resource, $storeManager, $metadataPool);
-    }
-
-    /**
-     * Load inventory data for a list of product ids and a given store.
-     * Expected rows structure : ['product_id', 'stock_status', 'qty'].
-     *
-     * @param integer $storeId    Store id.
-     * @param array   $productIds Product ids list.
-     *
-     * @return array
-     */
-    public function loadInventoryData($storeId, $productIds)
-    {
-        $websiteId = $this->getWebsiteId($storeId);
-        $stockId   = $this->getStockId($websiteId);
-        $tableName = $this->getStockIndexTableProvider()->execute($stockId);
-
-        $select = $this->getConnection()->select()
-            ->from(['product' => $this->getTable('catalog_product_entity')], [])
-            ->join(
-                ['stock_index' => $tableName],
-                'product.sku = stock_index.' . \Magento\InventoryIndexer\Indexer\IndexStructure::SKU,
-                [
-                    'product_id'    => 'product.entity_id',
-                    'stock_status'  => 'stock_index.' . \Magento\InventoryIndexer\Indexer\IndexStructure::IS_SALABLE,
-                    'qty'           => 'stock_index.' . \Magento\InventoryIndexer\Indexer\IndexStructure::QUANTITY,
-                ]
-            )
-            ->where('product.entity_id IN (?)', $productIds)
-            ->group('product.entity_id');
-
-        return $this->getConnection()->fetchAll($select);
-    }
-
-    /**
-     * Retrieve stock_id by website
-     *
-     * @param int $websiteId The website Id
-     *
-     * @return int
-     */
-    private function getStockId($websiteId)
-    {
-        if (!isset($this->stockIdByWebsite[$websiteId])) {
-            $websiteCode = $this->storeManager->getWebsite($websiteId)->getCode();
-            $stock = $this->getStockResolver()->execute(
-                \Magento\InventorySalesApi\Api\Data\SalesChannelInterface::TYPE_WEBSITE,
-                $websiteCode
-            );
-            $stockId = (int) $stock->getStockId();
-            $this->stockIdByWebsite[$websiteId] = $stockId;
-        }
-
-        return $this->stockIdByWebsite[$websiteId];
-    }
-
-    /**
-     * Retrieve Website Id by Store Id
-     *
-     * @param int $storeId The store id
-     *
-     * @return int
-     */
-    private function getWebsiteId($storeId)
-    {
-        return $this->storeManager->getStore($storeId)->getWebsiteId();
-    }
-
-    /**
-     * Fetch the Stock Resolver from Object Manager instead of constructor to avoid compilation error when MSI modules are not there.
-     * The fact that the class exists is normally already checked in the caller class.
-     * @see Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\InventoryData
-     *
-     * @return \Magento\InventorySalesApi\Api\StockResolverInterface|null
-     *
-     * @throws \Magento\Framework\Exception\RuntimeException
-     */
-    private function getStockResolver()
-    {
-        if (null === $this->stockResolver) {
-            try {
-                $this->stockResolver = $this->objectManager->get(\Magento\InventorySalesApi\Api\StockResolverInterface::class);
-            } catch (\Exception $exception) {
-                $message = 'Failed to fetch the MSI stock resolver despite the fact MSI implementation was considered as usable. ';
-                throw new \Magento\Framework\Exception\RuntimeException(__($message . $exception->getMessage()));
-            }
-        }
-
-        return $this->stockResolver;
-    }
-
-    /**
-     * Fetch the Stock Index Table Provider from Object Manager instead of constructor
-     * to avoid compilation error when MSI modules are not there.
-     *
-     * @return \Magento\InventorySalesApi\Api\StockResolverInterface|null
-     *
-     * @throws \Magento\Framework\Exception\RuntimeException
-     */
-    private function getStockIndexTableProvider()
-    {
-        if (null === $this->stockIndexTableProvider) {
-            try {
-                $this->stockIndexTableProvider = $this->objectManager->get(
-                    \Magento\InventoryIndexer\Model\StockIndexTableNameResolverInterface::class
-                );
-            } catch (\Exception $exception) {
-                $message = 'Failed to fetch the MSI stock table resolver despite the fact MSI implementation was considered as usable. ';
-                throw new \Magento\Framework\Exception\RuntimeException(__($message . $exception->getMessage()));
-            }
-        }
-
-        return $this->stockIndexTableProvider;
-    }
-}
diff --git src/module-elasticsuite-catalog/etc/di.xml src/module-elasticsuite-catalog/etc/di.xml
index d57b26b..9da4e8f 100644
--- src/module-elasticsuite-catalog/etc/di.xml
+++ src/module-elasticsuite-catalog/etc/di.xml
@@ -302,9 +302,6 @@
         </arguments>
     </type>
 
-    <preference for="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryDataInterface"
-                type="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryData" />
-
     <virtualType name="Smile\ElasticsuiteCatalog\Search\Request\Product\Coverage\Builder"
         type="\Smile\ElasticsuiteCore\Search\Request\Builder">
         <arguments>
```
