### ISSUE TITLE
mapper_parsing_exception: no type specified for property [option_text_activity]

### ISSUE THREAD

**Issue by prince-auriga** [Smile-SA/elasticsuite#154]
While trying to get indexing getting this error

**Comment by afoucret** [comment]
Hi @prince-auriga,

Thank you for reporting.

We will need more details if we to be be able to understand what happen there. Especially:

* your Magento version

* ElasticSuite version

* what where you doing when the exception occured (indexing, searching, ...)

* the full stacktrace from your logs

Thank you.

**Comment by afoucret** [comment]
Any news about this one ?

**Comment by afoucret** [comment]
Hi @prince-auriga,

Since we have no response from you, we will close this one.
Feel free to reopen if the problem is not solved and if you can provide us more details.

**Comment by danslo** [comment]
I'm also getting this issue when trying to reindex catalogsearch_fulltext:

``mapper_parsing_exception: no type specified for property [location]``

This is the full stacktrace:
```
mapper_parsing_exception: no type specified for property [location]
#0 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(640): Elasticsearch\Connections\Connection->tryDeserializeError(Array, 'Elasticsearch\\C...')
#1 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(561): Elasticsearch\Connections\Connection->tryDeserialize400Error(Array)
#2 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(262): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#3 /Users/danslo/Code/<removed>/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#4 /Users/danslo/Code/<removed>/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#5 /Users/danslo/Code/<removed>/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#6 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(283): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#7 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(159): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#8 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(99): Elasticsearch\Connections\Connection->performRequest('POST', '/magento2_defau...', Array, '{"settings":{"n...', Array, Object(Elasticsearch\Transport))
#9 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(79): Elasticsearch\Transport->performRequest('POST', '/magento2_defau...', Array, Array, Array)
#10 /Users/danslo/Code/<removed>/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(948): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#11 /Users/danslo/Code/<removed>/vendor/smile/elasticsuite/src/module-elasticsuite-core/Index/IndexOperation.php(148): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#12 /Users/danslo/Code/<removed>/vendor/smile/elasticsuite/src/module-elasticsuite-core/Indexer/GenericIndexerHandler.php(129): Smile\ElasticsuiteCore\Index\IndexOperation->createIndex('catalog_product', 1)
#13 /Users/danslo/Code/<removed>/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(110): Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler->cleanIndex(Array)
#14 /Users/danslo/Code/<removed>/vendor/magento/module-indexer/Model/Indexer.php(412): Magento\CatalogSearch\Model\Indexer\Fulltext->executeFull()
#15 /Users/danslo/Code/<removed>/vendor/magento/module-indexer/Console/Command/IndexerReindexCommand.php(57): Magento\Indexer\Model\Indexer->reindexAll()
#16 /Users/danslo/Code/<removed>/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Indexer\Console\Command\IndexerReindexCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/danslo/Code/<removed>/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/danslo/Code/<removed>/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Indexer\Console\Command\IndexerReindexCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /Users/danslo/Code/<removed>/vendor/magento/framework/Console/Cli.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /Users/danslo/Code/<removed>/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/danslo/Code/<removed>/bin/magento(23): Symfony\Component\Console\Application->run()
#22 {main}
```

The weird thing is that when I attached debugger and inspect the ``location`` property, it *does* have a type assigned to it. So I'm not quite sure what's going on:
![screen shot 2016-12-29 at 10 36 46](https://cloud.githubusercontent.com/assets/743661/21540867/becbb016-cdb2-11e6-8e27-7dea96f6ba03.png)

**Comment by danslo** [comment]
The problem is that ``standard`` analyzer is missing when ``getMultiFieldMappingPropertyConfig`` is called for location attribute. Why - I'm not sure :)

**Comment by danslo** [comment]
This happens when the attribute is not searchable, but *is* filterable/sortable. Then it gets assigned some analyzers but not standard analyzer. And this causes the field to be missing. Afterwards it's still "created" when adding copy_to information. That should only happen when field already exists.
