### ISSUE TITLE
Provide a fallback to default search when Elasticsearch is unreachable?

### ISSUE THREAD

**Issue by jreinke** [Smile-SA/elasticsuite#166]
Hi there and thanks for this great module!

I was just trying it out and I was wondering if it could not be useful to provide a fallback to Magento2 default search when Elasticsearch server is down?
Currently, we have a raw exception error displayed:

```
1 exception(s):
Exception #0 (Elasticsearch\Common\Exceptions\NoNodesAvailableException): No alive nodes found in your cluster

Exception #0 (Elasticsearch\Common\Exceptions\NoNodesAvailableException): No alive nodes found in your cluster
#0  /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1  /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\Transport->getConnection()
#2  /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(228): Elasticsearch\Transport->performRequest('HEAD', '/magento2_defau...', Array, NULL, Array)
#3  /Magento2/Source/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#4  /Magento2/Source/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#5  /Magento2/Source/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#6  /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(283): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#7  /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(159): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#8  /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(99): Elasticsearch\Connections\Connection->performRequest('HEAD', '/magento2_defau...', Array, NULL, Array, Object(Elasticsearch\Transport))
#9  /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(79): Elasticsearch\Transport->performRequest('HEAD', '/magento2_defau...', Array, NULL, Array)
#10 /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php(34): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#11 /Magento2/Source/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(46): Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest(Object(Elasticsearch\Endpoints\Indices\Exists))
#12 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-core/Index/IndexOperation.php(110): Elasticsearch\Namespaces\IndicesNamespace->exists(Array)
#13 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-core/Index/IndexOperation.php(124): Smile\ElasticsuiteCore\Index\IndexOperation->indexExists('catalog_product', Object(Magento\Store\Model\Store\Interceptor))
#14 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php(166): Smile\ElasticsuiteCore\Index\IndexOperation->getIndexByName('catalog_product', Object(Magento\Store\Model\Store\Interceptor))
#15 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php(108): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList->getMapping()
#16 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php(77): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList->getAttributeCollection()
#17 /Magento2/Source/vendor/magento/module-rule/Model/Condition/AbstractCondition.php(83): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product->loadAttributeOptions()
#18 /Magento2/Source/vendor/magento/module-rule/Model/Condition/Product/AbstractProduct.php(111): Magento\Rule\Model\Condition\AbstractCondition->__construct(Object(Magento\Rule\Model\Condition\Context), Array)
#19 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php(69): Magento\Rule\Model\Condition\Product\AbstractProduct->__construct(Object(Magento\Rule\Model\Condition\Context), Object(Magento\Backend\Helper\Data), Object(Magento\Eav\Model\Config), Object(Magento\Catalog\Model\ProductFactory), Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Magento\Eav\Model\ResourceModel\Entity\Attribute\Set\Collection), Object(Magento\Framework\Locale\Format), Array)
#20 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php(67): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product->__construct(Object(Magento\Rule\Model\Condition\Context), Object(Magento\Backend\Helper\Data), Object(Magento\Eav\Model\Config), Object(Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList), Object(Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\QueryBuilder), Object(Magento\Catalog\Model\ProductFactory), Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Magento\Eav\Model\ResourceModel\Entity\Attribute\Set\Collection), Object(Magento\Framework\Locale\Format), Array)
#21 /Magento2/Source/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Product->__construct(Object(Magento\Rule\Model\Condition\Context), Object(Magento\Backend\Helper\Data), Object(Magento\Eav\Model\Config), Object(Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList), Object(Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\QueryBuilder), Object(Magento\Catalog\Model\ProductFactory), Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Magento\Eav\Model\ResourceModel\Entity\Attribute\Set\Collection), Object(Magento\Framework\Locale\Format), Object(Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory), Array)
#22 /Magento2/Source/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Smile\\Elasticsu...', Array)
#23 /Magento2/Source/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Smile\\Elasticsu...', Array)
#24 /Magento2/Source/var/generation/Smile/ElasticsuiteCatalogRule/Model/Rule/Condition/ProductFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('Smile\\Elasticsu...', Array)
#25 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(191): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\ProductFactory->create(Array)
#26 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(121): Smile\ElasticsuiteVirtualCategory\Model\Rule->getStandardCategoryQuery(Object(Magento\Catalog\Model\Category\Interceptor))
#27 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php(96): Smile\ElasticsuiteVirtualCategory\Model\Rule->getCategorySearchQuery(Object(Magento\Catalog\Model\Category\Interceptor))
#28 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(98): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->applyCategoryFilterToCollection(Object(Magento\Catalog\Model\Category\Interceptor))
#29 /Magento2/Source/vendor/magento/module-layered-navigation/Block/Navigation.php(64): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->apply(Object(Magento\Framework\App\Request\Http))
#30 /Magento2/Source/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php(98): Magento\LayeredNavigation\Block\Navigation->_prepareLayout()
#31 /Magento2/Source/vendor/magento/framework/View/Element/AbstractBlock.php(264): Smile\ElasticsuiteCatalog\Block\Navigation->_prepareLayout()
#32 /Magento2/Source/vendor/magento/framework/View/Layout/Generator/Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#33 /Magento2/Source/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#34 /Magento2/Source/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#35 /Magento2/Source/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#36 /Magento2/Source/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#37 /Magento2/Source/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#38 /Magento2/Source/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#39 /Magento2/Source/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#40 /Magento2/Source/vendor/magento/framework/View/Page/Config.php(509): Magento\Framework\View\Page\Config->build()
#41 /Magento2/Source/var/generation/Magento/Framework/View/Page/Config/Interceptor.php(323): Magento\Framework\View\Page\Config->getElementAttribute('body', 'class')
#42 /Magento2/Source/vendor/magento/framework/View/Page/Config.php(467): Magento\Framework\View\Page\Config\Interceptor->getElementAttribute('body', 'class')
#43 /Magento2/Source/var/generation/Magento/Framework/View/Page/Config/Interceptor.php(297): Magento\Framework\View\Page\Config->addBodyClass('page-products')
#44 /Magento2/Source/vendor/magento/module-catalog/Controller/Category/View.php(199): Magento\Framework\View\Page\Config\Interceptor->addBodyClass('page-products')
#45 /Magento2/Source/var/generation/Magento/Catalog/Controller/Category/View/Interceptor.php(24): Magento\Catalog\Controller\Category\View->execute()
#46 /Magento2/Source/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Category\View\Interceptor->execute()
#47 /Magento2/Source/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('dispatch', Array)
#49 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'contextPlugin')
#50 /Magento2/Source/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#51 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'customer-app-ac...')
#53 /Magento2/Source/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#54 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#55 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'storeCheck')
#56 /Magento2/Source/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#57 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'weee-app-action...')
#59 /Magento2/Source/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#60 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#61 /Magento2/Source/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'tax-app-action-...')
#62 /Magento2/Source/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#63 /Magento2/Source/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#64 /Magento2/Source/var/generation/Magento/Catalog/Controller/Category/View/Interceptor.php(39): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('dispatch', Array, Array)
#65 /Magento2/Source/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Category\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#66 /Magento2/Source/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#67 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#68 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#69 /Magento2/Source/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#70 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#71 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#72 /Magento2/Source/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#73 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#74 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#75 /Magento2/Source/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#76 /Magento2/Source/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#77 /Magento2/Source/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#78 /Magento2/Source/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#79 /Magento2/Source/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#80 /Magento2/Source/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#81 /Magento2/Source/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#82 /Magento2/Source/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#83 /Magento2/Source/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#84 {main}
```

**Comment by afoucret** [comment]
Hi @jreinke,

First thank you for your module for Magento 1.x. It was great source inspiration for us and the current module would not be there without your work !!!

About fallbacking, this is not something Magento does for it's own ElasticSearch implementation (neither on it's SolR implementation). 

Then this is not something we want to move forward on since : 
* Fallbacking require double indexing of the search engine in both ES and MySQL. We try to avoid this since we have some catalog with millions products.
* Our module provides several features that will simply not work with a MySQL engine (virtual categories, ....). It will be very hard to have a consistent behavior between the engines

Instead we advice people who want a better fallback to use ES in cluster mode.

**Comment by afoucret** [comment]
Hi @jreinke,

I will close this one since we do not plan any work on this.

Best regards,

**Comment by jreinke** [comment]
Hi @afoucret,

Thanks for your message. I understand your point of view.

Maybe the exception could be caught with a clean message to avoid blocking navigation.

**Comment by afoucret** [comment]
Hi @jreinke,

I will think about this.

Thank you for reporting.
