### ISSUE TITLE
Error when first index catalogsearch_fulltext

### ISSUE THREAD

**Issue by AKALuffy** [Smile-SA/elasticsuite#182]
Hello,

I just install elasticsearch + elasticsuite on a magento 2.1.0. 

I follow your wiki to install elasticsearch with plugin, all is fine on this.
I install elasticsuite with composer.

I run bin/magento setup:upgrade ( work fine ).

But when I want to bin/magento indexer:reindex catalogsearch_fulltext.

I got this error : 

Catalog Search indexer process unknown error:
mapper_parsing_exception: no type specified for property [option_text_customizable]

When I look elasticsearch.log i got this trace : 

`[2016-10-25 18:01:01,698][DEBUG][action.admin.indices.create] [Shadow-Hunter] [magento2_default_catalog_product_20161025_160101] failed to create
MapperParsingException[Failed to parse mapping [product]: no type specified for property [option_text_customizable]]; nested: MapperParsingException[no type specified for property [option_text_customizable]];
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:291)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:317)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: MapperParsingException[no type specified for property [option_text_customizable]]
        at org.elasticsearch.index.mapper.core.TypeParsers$1.parse(TypeParsers.java:91)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:309)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:222)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:549)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:319)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:289)
        ... 9 more
`

**Comment by romainruaud** [comment]
Hello @AKALuffy and thank your for trying out our module.

Could you post a picture of your "customizable" attribute configuration in the back office ?

And also the lines concerning this attribute on the eav_attribute and catalog_eav_attribute table.

Regards,

**Comment by AKALuffy** [comment]
Hello,

I got 374 custom attribute. How can I know which one provoke this issue ?

Regards

**Comment by romainruaud** [comment]
``option_text_customizable`` means the problematic attribute is the one which is called "customizable".

Regards,

**Comment by AKALuffy** [comment]
Oh ok thanks. I will check this.

**Comment by anethum** [comment]
@romainruaud I have the same issue with different attributes, like option_text_diameter or option_text_typ
