### ISSUE TITLE
Category REST API: Exceptions being thrown due to faulty annotations.

### ISSUE THREAD

**Issue by TiEul** [Smile-SA/elasticsuite#186]
Hey, 

I am getting a bunch of errors related to faulty annotations which apparently kill the whole REST API chain. So, by sending the following rather simple CURL, for example:

`curl -X PUT "host.name/index.php/rest/V1/categories/20" -H "Content-Type:application/json" -H "Authorization: Bearer nl5qpyj1xmq25vvw38masq66li6l7k4p" -d '{"category":{"name":"Some Name","isActive":false}}' | json_pp  `

I receive the following trace as a response:

```
   "trace" : "#0 /var/www/customername/vendor/magento/framework/Reflection/MethodsMap.php(163): Magento\\Framework\\Reflection\\TypeProcessor->getGetterReturnType(Object(Zend\\Code\\Reflection\\MethodReflection))\n#1 /var/www/customername/vendor/magento/framework/Reflection/MethodsMap.php(100): Magento\\Framework\\Reflection\\MethodsMap->getMethodMapViaReflection('Smile\\\\Elasticsu...')\n#2 /var/www/customername/vendor/magento/framework/Reflection/DataObjectProcessor.php(77): Magento\\Framework\\Reflection\\MethodsMap->getMethodsMap('Smile\\\\Elasticsu...')\n#3 /var/www/customername/vendor/magento/framework/Reflection/CustomAttributesProcessor.php(79): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(Smile\\ElasticsuiteVirtualCategory\\Model\\Rule), 'Smile\\\\Elasticsu...')\n#4 /var/www/customername/vendor/magento/framework/Reflection/CustomAttributesProcessor.php(56): Magento\\Framework\\Reflection\\CustomAttributesProcessor->convertCustomAttribute(Object(Magento\\Framework\\Api\\AttributeValue), '\\\\Magento\\\\Catalo...')\n#5 /var/www/customername/var/generation/Magento/Framework/Reflection/CustomAttributesProcessor/Proxy.php(95): Magento\\Framework\\Reflection\\CustomAttributesProcessor->buildOutputDataArray(Object(customername\\Catalog\\Model\\Category\\Interceptor), '\\\\Magento\\\\Catalo...')\n#6 /var/www/customername/vendor/magento/framework/Reflection/DataObjectProcessor.php(102): Magento\\Framework\\Reflection\\CustomAttributesProcessor\\Proxy->buildOutputDataArray(Object(customername\\Catalog\\Model\\Category\\Interceptor), '\\\\Magento\\\\Catalo...')\n#7 /var/www/customername/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(107): Magento\\Framework\\Reflection\\DataObjectProcessor->buildOutputDataArray(Object(customername\\Catalog\\Model\\Category\\Interceptor), '\\\\Magento\\\\Catalo...')\n#8 /var/www/customername/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(59): Magento\\Framework\\Webapi\\ServiceOutputProcessor->convertValue(Object(customername\\Catalog\\Model\\Category\\Interceptor), '\\\\Magento\\\\Catalo...')\n#9 /var/www/customername/vendor/magento/module-webapi/Controller/Rest.php(308): Magento\\Framework\\Webapi\\ServiceOutputProcessor->process(Object(customername\\Catalog\\Model\\Category\\Interceptor), 'Magento\\\\Catalog...', 'save')\n#10 /var/www/customername/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#11 /var/www/customername/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 /var/www/customername/vendor/magento/framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#13 /var/www/customername/vendor/magento/framework/App/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#14 /var/www/customername/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#15 {main}",
   "message" : "Getter return type must be specified using @return annotation. See Smile\\ElasticsuiteCatalogRule\\Model\\Rule::getConditionsInstance()"
```
Specifically the last line hints at annotation issues with the ElasticSuite module. Apparently it considers the `{@inheritdoc}` annotations to be invalid and expects proper `@return X` annotations, though I am not sure if this is the actual problem and not just some side-effect of another issue. 

I have tested the same on another local Magento 2 environment of mine which does not have ElasticSuite installed and the same type of requests work fine there.

**Comment by afoucret** [comment]
The PR #196 fix this one have been merged into branches 2.2.x branch and you can use it now.
It will be available into the both next minor release (2.2.3) and major release (2.3.0).
