### ISSUE TITLE
cannot install plugin Java Error at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPlu ginCommand.java:375

### ISSUE THREAD

**Issue by waseem5222** [Smile-SA/elasticsuite#1892]
![elasticsearch](https://user-images.githubusercontent.com/19758327/88677283-b680e480-d10a-11ea-9daf-b44c7d6f6159.jpg)

Installing the ICU analysis 7.3.1. for Elastic Search 7.3.1 unfortunately I am getting a java error
### Preconditions

Microsoft Server 2012

Magento Version :no

ElasticSuite Version : 7.3.1

Environment :

Third party modules :

### Steps to reproduce

1.C:\Program Files\Elastic\Elasticsearch\7.3.1\bin>elasticsearch-plugin.bat instal
l path\analysis-icu-7.3.1.zip
-> Downloading path\analysis-icu-7.3.1.zip
Exception in thread "main" java.net.MalformedURLException: unknown protocol: c
        at java.base/java.net.URL.<init>(URL.java:652)
        at java.base/java.net.URL.<init>(URL.java:541)
        at java.base/java.net.URL.<init>(URL.java:488)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPlu
ginCommand.java:375)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPlugin
Command.java:278)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginC
ommand.java:229)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginC
ommand.java:216)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwar
eCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:1
24)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:1
24)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
2.
3.

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Hi, 

we do not provide support for Elasticsearch himself, especially on windows.

Please head your request here : https://discuss.elastic.co/

regards
