### ISSUE TITLE
Occassional error on order success page related to saferpay / customweb module, maybe related to elasticsuite-tracker

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#2096]
We have very few orders which get canceled on the success page.

### Preconditions

Magento Version : 2.3.4-p2

ElasticSuite Version :2.8.10

Environment : production

Third party modules : SaferPay Module by custom web

### Steps to reproduce
The issue is not reproducible clearly

1. Make an order
2. Pay
3. Return to order success page
### Expected result

1. All fine

### Actual result

Server error on the order success page, order is canceled 

[Sun Mar 07 22:02:47.646126 2021] [php7:error] [pid 29970] [client 45.12.50.193:47978] PHP Fatal error:  Uncaught Error: Call to a member function getMethod() on null in /var/www/html/shop.example.com/web/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Block/Variables/Page/Order.php:74\nStack trace:\n#0 /var/www/html/shop.example.com/web/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/view/frontend/templates/variables/page.phtml(18): Smile\\ElasticsuiteTracker\\Block\\Variables\\Page\\Order->getVariables()\n#1 /var/www/html/shop.example.com/web/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/s...')\n#2 /var/www/html/shop.example.com/web/vendor/magento/framework/View/Element/Template.php(271): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(Smile\\ElasticsuiteTracker\\Block\\Variables\\Page\\Order\\Interceptor), '/var/www/html/s...', Array)\n#3 /var/www/html/shop.example.com/web/vendor/magento/framework/View/Element/Template.php(301): Magento\\Framework\\View\\Element\\Template->fetchView('/var/www/html/s...')\n#4 /var/www/html/shop.example.com/web/vendor/magento/framework/View/Element/Abst in /var/www/html/shop.example.com/web/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Block/Variables/Page/Order.php on line 74, referer: https://www.saferpay.com/VT2/mpp/Confirmation/Index/euvXXXXXXXXXXX

### Guesswork

That line is like this:

    $variables['order.payment_method']  = $order->getPayment()->getMethod();

So somehow the payment info must get lost.

Did anybody see this before happning? Should we just check in the tracker module if the payment object is available?

**Comment by romainruaud** [comment]
Looks like https://github.com/Smile-SA/elasticsuite/pull/2030

Maybe we should merge this one

**Comment by amenk** [comment]
Still wondering if a check for `getPayment() !== null` would be necessary in https://github.com/Smile-SA/elasticsuite/pull/2030/files#diff-4f698766a5bc758396da4fae195c0da59392dfbe830c991d39b3a7b9a29fa874R74 as a safeguard.

I also don't know if the exception in the elasticsuite module is caused by the payment module doing something strange or if the exception in the smilesa module on the success page causes the order to be canceled.
