### ISSUE TITLE
Virtual category error

### ISSUE THREAD

**Issue by NuggetsMaster** [Smile-SA/elasticsuite#2261]
# Call to a member function getAllIds() on array

### Preconditions

Magento Version : Magento ver. 2.3.6-p1 CE

ElasticSuite Version : 2.9.7

ElasticSearch Version : 7.13.4

Environment : Production

### What happens

When i try to access to my virtual category page in frontend i got this error : 

`2021/09/22 11:25:19 [error] 25671#25671: *434981 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getAllIds() on array in /home/www/budracing/www/releases/20210916145725/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php:147
Stack trace:
#0 /home/www/budracing/www/releases/20210916145725/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php(108): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Product->getCategorySearchQuery(Array, '128')
#1 /home/www/budracing/www/releases/20210916145725/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Combine.php(50): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Product->getSearchQuery(Array, '128')
#2 /home/www/budracing/www/releases/20210916145725/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(285): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Combine->getSearchQuery(Array, '128')
#3 /home/ww" while reading response header from upstream, client: 80.11.204.181, server: m2.bud-racing.com, request: "GET /fr/nouveautes.html HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm-budstage.sock:", host: "m2.bud-racing.com", referrer: "https://m2.bud-racing.com/"`

the function getCategorySearchQuery is used on the category with id 128 wich is the root category

Thanks for help

**Comment by vahonc** [comment]
Hello @NuggetsMaster,

Could you please provide more details (screenshots) about your test case, how is configured your virtual category, which rule condition you are using, and what is displayed in the "Products List Preview" tab.

BR,
Vadym

**Comment by NuggetsMaster** [comment]
Hello @vahonc thanks for your reply, 


### My test case is simple i try to access tu the catalog (listing) page of the virtual category in my case its :  https://m2.bud-racing.com/fr/nouveautes.html

Sometimes i got the same error when i try to use the search, when i got the error i go to the administration and i resave the root category and the problem is resolved but it doesnt work for the virtual category listing page


### Here is my virtual category configuration : 
![config](https://user-images.githubusercontent.com/53437040/134526000-f9d60226-52e9-45d2-be27-e70a6141d4e5.PNG)

### Here is my conditions and the products that match the rules 
![products](https://user-images.githubusercontent.com/53437040/134526274-24d3fa66-5494-42ab-b84c-eae339511dcf.PNG)

Thanks for help.
BR

**Comment by vahonc** [comment]
@NuggetsMaster according to this comment:

> the function getCategorySearchQuery is used on the category with id 128 which is the root category

I guess that you have an environment with multiple websites or stores. If so, please check if everything is properly configured. Also you could check it on different websites or stores if your issue occurs on them too.

And the last, could you tell me if you are using a Flat Catalog (categories) in your environment?

BR,
Vadym

**Comment by NuggetsMaster** [comment]
Hello @vahonc 
> guess that you have an environment with multiple websites or stores

Yes we have 2 websites, 

- 1 website with 2 store both of them has the error 
- 1 website with 1 store and it work properly without any error

> And the last, could you tell me if you are using a Flat Catalog (categories) in your environment?

Yes we use flat catalog for categories but not for product

Thanks for help
BR

**Comment by vahonc** [comment]
Hello @NuggetsMaster,

According to the Magento [Docs](https://docs.magento.com/user-guide/catalog/catalog-flat.html), using of a flat catalog is no longer recommended as a best practice. A detailed description and solution is available in their [Help Center](https://support.magento.com/hc/en-us/articles/360034631192?_ga=2.28679545.493004475.1632748673-1168946165.1623998361). 

Therefore if it's possible try to Set `Use Flat Catalog Category` to _No_. 

Anyway, I'll also try to reproduce your issue on my local test environment.

BR,
Vadym

**Comment by NuggetsMaster** [comment]
Hello @vahonc 

I have tried to disable flat catalog for categories but now im getting the error 
> main.CRITICAL: Warning: call_user_func_array() expects parameter 1 to be a valid callback, class '{"type":"Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine","attribute":null,"operator":null,"value":"1","is_value_processed":null,"aggregator":"all"}' not found


Thanks for help
BR

**Comment by vahonc** [comment]
Hello @NuggetsMaster,

Are you getting this error when you try to access your virtual category on the front?

Have you tried running these commands after disabling the flat directory for categories?
<pre>
$ bin/magento cache:flush or $ bin/magento cache:clean
$ bin/magento setup:di:compile
$ bin/magento indexer:reindex
</pre>

Also please provide an extract of the queries that are being sent to ES when you are browsing categories. You can get it from the `system.log` file if you activate the **Debug mode** of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`

BR,
Vadym

**Comment by NuggetsMaster** [comment]
hello @vahonc 
Yes i have tried all these commands and the problem is still here.

The problem is happening when i try to access to any category, classic or virtual

Here is some request send to ES for a classic category : 

> [2021-10-04 12:00:55] main.INFO: curl -XPOST 'http://localhost:9200/m2dev_fr_catalog_product/_search?pretty=true' -d '{"size":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"bool":{"must_not":[{"term":{"category.is_virtual":{"value":true,"boost":1}}}],"boost":1}},{"terms":{"category.category_id":["206"],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},{"terms":{"visibility":[2,4],"boost":1}},{"bool":{"must_not":[{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"term":{"category.category_id":{"value":206,"boost":1}}},{"term":{"category.is_blacklisted":{"value":true,"boost":1}}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":100000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":100000,"order":{"_count":"desc"}}}},"track_total_hits":true}' [] []

Another request : 

> [2021-10-04 12:04:14] main.INFO: curl -XPOST 'http://localhost:9200/m2dev_fr_catalog_product/_search?pretty=true' -d '{"size":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"terms":{"visibility":[2,4],"boost":1}},{"bool":{"must_not":[{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"term":{"category.category_id":{"value":2,"boost":1}}},{"term":{"category.is_blacklisted":{"value":true,"boost":1}}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}},{"nested":{"path":"category","score_mode":"none","query":{"terms":{"category.category_id":["2"],"boost":1}},"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":100000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":100000,"order":{"_count":"desc"}}}},"track_total_hits":true}' [] []

And one for virtual category : 

> [2021-10-04 12:05:53] main.INFO: curl -XPOST 'http://localhost:9200/m2dev_fr_catalog_product/_search?pretty=true' -d '{"size":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"bool":{"must_not":[{"term":{"category.is_virtual":{"value":true,"boost":1}}}],"boost":1}},{"terms":{"category.category_id":["95"],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"must_not":[],"should":[],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}},{"bool":{"must_not":[{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"term":{"category.category_id":{"value":471,"boost":1}}},{"term":{"category.is_blacklisted":{"value":true,"boost":1}}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":100000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":100000,"order":{"_count":"desc"}}}},"track_total_hits":true}' [] []

Thanks for help ,
BR

**Comment by vahonc** [comment]
@NuggetsMaster, I was trying to reproduce your issue on a similar test environment (Magento CE 2.3.7-p1 and ES 2.9.7)but with only one store. So with setting  `Use Flat Catalog Category` to _YES_ I've also got an error like `Error: Call to a member function getAllIds() on array in` when I tried to get access to my virtual category but all is fine with access to all classic categories and to virtual with simple rule conditions. And when I set `Use Flat Catalog Category` to _NO_ I could get access to any categories.

However, I will try to find a workaround to fix `function getAllIds() in .../src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php:147`

BR,
Vadym

**Comment by NuggetsMaster** [comment]
@vahonc Nice so we have the error with `Use Flat Catalog Category `set to YES thanks for your invest in my problem. if you find a solution with these settings it will solve my problem 


NB : im on Magento CE ver. 2.3.6-p1 not  Magento CE 2.3.7-p1 but it doesn't seems important

Thanks for help,
BR

**Comment by NuggetsMaster** [comment]
Hello @vahonc,

Do you know when the bug will be fix and a new version released ? 

Thanks for help.
BR
