### ISSUE TITLE
Optimizer rule using a deleted category in conditions causes failure

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#2599]
### Preconditions

Magento Version : 2.4.3 (not sure it's relevant, probably all versions are affected)

ElasticSuite Version : 2.10.x

Environment : Dev / Prod

Third party modules : None

### Steps to reproduce

1. Create an optimizer
2. Associate this optimizer to both Catalog Product View and Quick Search Form
3. In the "apply to products", build on condition based on a Category, and select one or more categories.
4. Delete one of these categories
5. Go to the frontend, search for anything or browse to a category

### Expected result

1. Eveyrthing is operating normally

### Actual result

1. There is a fatal error
2. Error message is : 

Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): No such entity with id =  at /var/www/magento/releases/magento-production_2-21_20220523_1658/vendor/magento/framework/Exception/NoSuchEntityException.php:50

The last lines of the stack trace are : 

```
#1 /var/www/magento/releases/magento-production_2-21_20220523_1658/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php(151): Magento\Catalog\Model\CategoryRepository->get()
#2 /var/www/magento/releases/magento-production_2-21_20220523_1658/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php(108): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Product->getCategorySearchQuery()
#3 /var/www/magento/releases/magento-production_2-21_20220523_1658/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Combine.php(50): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Product->getSearchQuery()
#4 /var/www/magento/releases/magento-production_2-21_20220523_1658/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule.php(125): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Combine->getSearchQuery()

```

**Comment by romainruaud** [comment]
I think we should "just" catch this NoSuchEntityException in such cases.

But we'll need to find where it's triggered in this case, to begin with.
