### ISSUE TITLE
Virtual category subtree "Clear on array"

### ISSUE THREAD

**Issue by julienanquetil** [Smile-SA/elasticsuite#2616]
We have a virtual category setup like "If product are from Brand A, B , C..". Everything works as expected. If we want to include the "subtree" by switching on the feature on the backend, we got an error.
### Preconditions

![Capture d’écran 2022-06-24 à 11 24 59](https://user-images.githubusercontent.com/1108170/175512248-60b93ae0-2dca-4fb4-a8ee-d06d5bd4ad84.png)

Magento Version : 2.4.3-p1

ElasticSuite Version : 2.10.10 / Hyva compatibility module 1.1.2

Environment : QA

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1. have the filter by category enabled

### Actual result

1. [Screenshot, logs]
An error has happened during application run. See exception log for details.

```

[2022-06-24 07:47:41] main.CRITICAL: Error: Call to a member function clear() on array in /srv/www/magento/releases/20220624065050/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php:131
Stack trace:
#0 /srv/www/magento/releases/20220624065050/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(153): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->getChildrenCategories()
#1 /srv/www/magento/releases/20220624065050/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(197): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->_getItemsData()
#2 /srv/www/magento/releases/20220624065050/vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php(159): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->_initItems()
#3 /srv/www/magento/releases/20220624065050/vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php(148): Magento\Catalog\Model\Layer\Filter\AbstractFilter->getItems()
#4 /srv/www/magento/releases/20220624065050/vendor/magento/module-catalog/Model/Layer/Category/AvailabilityFlag.php(33): Magento\Catalog\Model\Layer\Filter\AbstractFilter->getItemsCount()
#5 /srv/www/magento/releases/20220624065050/vendor/magento/module-catalog/Model/Layer/Category/AvailabilityFlag.php(23): Magento\Catalog\Model\Layer\Category\AvailabilityFlag->canShowOptions(Array)
#6 /srv/www/magento/releases/20220624065050/vendor/magento/module-layered-navigation/Block/Navigation.php(126): Magento\Catalog\Model\Layer\Category\AvailabilityFlag->isEnabled(Object(Magento\Catalog\Model\Layer\Category\Interceptor), Array)
#7 /srv/www/magento/releases/20220624065050/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php(83): Magento\LayeredNavigation\Block\Navigation->canShowBlock()
#8 /srv/www/magento/releases/20220624065050/app/design/frontend/EcomFR/megadental/Hyva_SmileElasticsuite/templates/catalog/layer/view.phtml(24): Smile\ElasticsuiteCatalog\Block\Navigation->canShowBlock()
#9 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/srv/www/magent...')
#10 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Smile\ElasticsuiteCatalog\Block\Navigation), '/srv/www/magent...', Array)
#11 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#12 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Smile\ElasticsuiteCatalog\Block\Navigation), '/srv/www/magent...', Array)
#13 /srv/www/magento/releases/20220624065050/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)
#14 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Smile\ElasticsuiteCatalog\Block\Navigation), '/srv/www/magent...', Array)
#15 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/srv/www/magent...')
#16 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#17 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#18 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#19 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('catalog.leftnav')
#21 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('catalog.leftnav')
#22 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('catalog.leftnav', false)
#23 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('sidebar.main', false)
#24 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('sidebar.main')
#25 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('sidebar.main', false)
#26 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('div.sidebar.mai...', false)
#27 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('div.sidebar.mai...')
#28 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('div.sidebar.mai...', false)
#29 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('columns', false)
#30 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#31 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('columns', false)
#32 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#33 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#34 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('main.content', false)
#35 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#36 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#37 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#38 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#39 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('root')
#40 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')
#41 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#42 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#43 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#44 /srv/www/magento/releases/20220624065050/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#45 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#46 /srv/www/magento/releases/20220624065050/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#47 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#48 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#49 /srv/www/magento/releases/20220624065050/vendor/amasty/gdpr-cookie/Plugin/ProcessPageResult.php(64): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#50 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\GdprCookie\Plugin\ProcessPageResult->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#51 /srv/www/magento/releases/20220624065050/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#52 /srv/www/magento/releases/20220624065050/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, NULL)
#53 /srv/www/magento/releases/20220624065050/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#54 /srv/www/magento/releases/20220624065050/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#55 /srv/www/magento/releases/20220624065050/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#56 {main}

```

**Comment by romainruaud** [comment]
Hi @julienanquetil 

->getChildrenCategories() might return an array if you are using "Flat Categories". Is it the case in your project ?

Regards

**Comment by julienanquetil** [comment]
We didn’t have flat category enabled, so we should turn it on ? Thanks
