### ISSUE TITLE
[swatches] Array to string conversion

### ISSUE THREAD

**Issue by sheepfy** [Smile-SA/elasticsuite#2619]
1. Blank magento with sample data + smile latest version.
2. go to women/bottoms-women/pants-women (or whatever place with color or swatches)
3. click a color in order to add ?color=Blue in the url

Expected result:
display correct filtered products

Actual result:
Array to string conversion:
1 exception(s):
Exception #0 (Exception): Warning: Array to string conversion in /magentohome/vendor/magento/module-swatches/Helper/Data.php on line 199

Exception #0 (Exception): Warning: Array to string conversion in /magentohome/vendor/magento/module-swatches/Helper/Data.php on line 199
<pre>#1 array_diff_assoc() called at [vendor/magento/module-swatches/Helper/Data.php:199]
#2 Magento\Swatches\Helper\Data->loadFirstVariation() called at [vendor/magento/module-swatches/Helper/Data.php:231]
#3 Magento\Swatches\Helper\Data->loadFirstVariationWithImage() called at [vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php:102]
#4 Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->loadSimpleVariation() called at [vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php:48]
#5 Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->beforeGetImage() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#6 Magento\Catalog\Block\Product\ListProduct\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Magento\Catalog\Block\Product\ListProduct\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php:329]
#8 Magento\Catalog\Block\Product\ListProduct\Interceptor->getImage() called at [vendor/magento/module-catalog/view/frontend/templates/product/list.phtml:56]
#9 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]

I have somehow noticed that this can be fixed by replacing 
src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php::getFilterArray method with the original method, or commenting these lines:

//                if (isset($filterArray[$code]) && !is_array($filterArray[$code])) {
//                    $filterArray[$code] = [$filterArray[$code]];
//                }
//
//                if ($attribute->getId() && $this->canReplaceImageWithSwatch($attribute)) {
//                    $filterArray[$code][] = $this->swatchHelperData->getOptionIds($attribute, $value);
//                }

I am not exactly sure what should happen in here. I have not dug that much.

**Comment by sheepfy** [comment]
I have somehow noticed that this can be fixed by replacing 
src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php::getFilterArray method with the original method, or commenting these lines:

//                if (isset($filterArray[$code]) && !is_array($filterArray[$code])) {
//                    $filterArray[$code] = [$filterArray[$code]];
//                }
//
//                if ($attribute->getId() && $this->canReplaceImageWithSwatch($attribute)) {
//                    $filterArray[$code][] = $this->swatchHelperData->getOptionIds($attribute, $value);
//                }

I am not exactly sure what should happen in here. I have not dug that much.

**Comment by vahonc** [comment]
@sheepfy, thanks for your feedback. 

It looks like this issue could be linked to PHP 8 compatibility. I'll try to dig into it more. 

BR,
Vadym

**Comment by sheepfy** [comment]
@vahonc 
If you need, we can setup a sharescreen too, just let me know.

**Comment by vahonc** [comment]
Hi @sheepfy,

Unfortunately, I was not able to reproduce your issue.

I installed fresh Magento 2.4.4 CE with default sample data and ElasticSuite 2.10.10, of course, I use PHP 8.1. 

So, when I go to `women/bottoms-women/pants-women` category and click on blue color in order to add `?color=Blue` to the URL 
It showed me the correct filtered products without any errors. Please look at my screenshot below:
![Screenshot from 2022-07-04 14-09-24](https://user-images.githubusercontent.com/67791361/177151084-8391d40f-ab48-4a65-bccf-668c36bcf08c.png)

Have you tried to check how working color filtration before installing the ElasticSuite module, perhaps something is wrong with installed sample data? I checked it before and after installation ES and in both cases I see results which I expected.

Here're my steps for installation (maybe it will be useful for you):
<pre>
$ composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.4

$ bin/magento sampledata:deploy

$ bin/magento setup:install with params

$ bin/magento setup:upgrade
$ bin/magento setup:di:compile
$ bin/magento setup:static-content:deploy -f
$ bin/magento indexer:reindex
$ bin/magento cache:clean

$ composer require smile/elasticsuite ~2.10.0
$ bin/magento setup:upgrade
$ bin/magento indexer:reindex
$ bin/magento cache:clean
</pre>

BR,
Vadym

**Comment by evktalo** [comment]
In case it helps, we had this issue (version 2.9.5) and the bug was triggered by a configurable's subproduct having no product image. So adding the image solved the issue as a workaround.

**Comment by evktalo** [comment]
btw the code causing this issue seems to be https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php and that is marked as deprecated since Magento 2.1.6 , so I assume it could be removed?

**Comment by Amadeco** [comment]
> btw the code causing this issue seems to be https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php and that is marked as deprecated since Magento 2.1.6 , so I assume it could be removed?

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <!-- Smile_ElasticsuiteSwatches -->
    <type name="Magento\Catalog\Block\Product\ListProduct">
        <plugin name="add_product_object_to_image_data_array" disabled="true" />
    </type>
    <type name="Magento\CatalogSearch\Block\SearchResult\ListProduct">
        <plugin name="add_product_object_to_image_data_array" disabled="true" />
    </type>
</config>
```

Solved my issue on Magento 2.4.7 and with child products with no images.

**Comment by cptX** [comment]
Same problem in Magento 2.4.8-p3. Just upgraded to the new version and I have this error (With 2.4.7-p3 it was working).
I cannot access my admin panel at all!!! Please help, it's a production site!

`Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/mywebsite/vendor/magento/module-swatches/Helper/Data.php(200): array_diff_assoc()
#2 /var/www/mywebsite/vendor/magento/module-swatches/Helper/Data.php(232): Magento\Swatches\Helper\Data->loadFirstVariation()
#3 /var/www/mywebsite/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php(101): Magento\Swatches\Helper\Data->loadFirstVariationWithImage()
#4 /var/www/mywebsite/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php(47): Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->loadSimpleVariation()
#5 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(121): Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->beforeGetImage()
#6 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Block\Product\ListProduct\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/mywebsite/generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php(23): Magento\Catalog\Block\Product\ListProduct\Interceptor->___callPlugins()
#8 /var/www/mywebsite/var/view_preprocessed/pub/static/vendor/magento/module-catalog/view/frontend/templates/product/list.phtml(1): Magento\Catalog\Block\Product\ListProduct\Interceptor->getImage()
#9 /var/www/mywebsite/vendor/magento/framework/View/TemplateEngine/Php.php(67): include('...')
#10 /var/www/mywebsite/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#11 /var/www/mywebsite/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#12 /var/www/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(1128): Magento\Framework\View\Element\Template->_toHtml()
#13 /var/www/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(1132): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#14 /var/www/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(676): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#15 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#17 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#18 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#19 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#20 /var/www/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(523): Magento\Framework\View\Layout\Interceptor->renderElement()
#21 /var/www/mywebsite/vendor/magento/module-catalog/Block/Category/View.php(128): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#22 /var/www/mywebsite/var/view_preprocessed/pub/static/vendor/magento/module-catalog/view/frontend/templates/category/products.phtml(1): Magento\Catalog\Block\Category\View->getProductListHtml()
#23 /var/www/mywebsite/vendor/magento/framework/View/TemplateEngine/Php.php(67): include('...')
#24 /var/www/mywebsite/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#25 /var/www/mywebsite/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#26 /var/www/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(1128): Magento\Framework\View\Element\Template->_toHtml()
#27 /var/www/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(1132): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#28 /var/www/mywebsite/vendor/magento/framework/View/Element/AbstractBlock.php(676): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#29 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#30 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#31 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#32 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#33 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#34 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#35 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#36 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#37 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#38 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#39 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#40 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#41 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#42 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#43 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#44 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#45 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#46 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#47 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#48 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#49 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#50 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#51 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#52 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#53 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#54 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#55 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#56 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#57 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#58 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#59 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#60 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#61 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#62 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#63 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#64 /var/www/mywebsite/vendor/magento/framework/View/Layout.php(978): Magento\Framework\View\Layout\Interceptor->renderElement()
#65 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#66 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#67 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#68 /var/www/mywebsite/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#69 /var/www/mywebsite/vendor/magento/framework/View/Result/Page.php(284): Magento\Framework\View\Layout\Interceptor->getOutput()
#70 /var/www/mywebsite/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#71 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#72 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#73 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#74 /var/www/mywebsite/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#75 /var/www/mywebsite/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#76 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#77 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#78 /var/www/mywebsite/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#79 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#80 /var/www/mywebsite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#81 /var/www/mywebsite/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#82 /var/www/mywebsite/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#83 /var/www/mywebsite/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#84 {main} {"exception":"[object] (Exception(code: 0): Warning: Array to string conversion in /var/www/mywebsite/vendor/magento/module-swatches/Helper/Data.php on line 200 at /var/www/mywebsite/vendor/magento/framework/App/ErrorHandler.php:61)"} []`
