### ISSUE TITLE
Compiling error on Interface after installing ElasticSuite

### ISSUE THREAD

**Issue by henkvalk** [Smile-SA/elasticsuite#2642]
I want to replace the Amasty Shopby with Smile ElasticSuite, but I receive an error on compiling.

I removed the generated folder before compiling, but this has no effect.
 
The following  occurred:

```
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 128.0 MiB
PHP Fatal error:  Uncaught Error: Interface 'Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\LayerBuilderInterface' not found in /data/web/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Category.php:33
Stack trace:
#0 /data/web/magento2/vendor/composer/ClassLoader.php(571): include()
#1 /data/web/magento2/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/data/web...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Smile\\Elasticsu...')
#3 [internal function]: spl_autoload_call('Smile\\Elasticsu...')
#4 /data/web/magento2setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Smile\\Elasticsu...')
#5 /data/web/magento2setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Smile\\El in /data/web/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Category.php on line 33

Fatal error: Uncaught Error: Interface 'Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\LayerBuilderInterface' not found in /data/web/magento2smile/elasticsuite/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Category.php:33
Stack trace:
#0 /data/web/magento2vendor/composer/ClassLoader.php(571): include()
#1 /data/web/magento2vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/data/web...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Smile\\Elasticsu...')
#3 [internal function]: spl_autoload_call('Smile\\Elasticsu...')
#4 /data/web/magento2setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Smile\\Elasticsu...')
#5 /data/web/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Smile\\El in /data/web/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Category.php on line 33
```

Setup :
- magento/product-community-edition 2.4.2
- smile/elasticsuite: 2.10.10 

What I'm doing wrong?

**Comment by henkvalk** [comment]
The problem was the graph-ql modules were replaced in composer.json. Now it's fine
