### ISSUE TITLE
Conflict with theme

### ISSUE THREAD

**Issue by nikonratm** [Smile-SA/elasticsuite#271]
I installed a commercial theme on my site and now am getting this error in the logs. Any thoughts? Thanks so much

```
[2016-12-30 16:24:55] main.CRITICAL: exception 'Exception' with message 'Recoverable Error: Argument 1 passed to Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage::__construct() must be an instance of Smile\ElasticsuiteSwatches\Helper\Swatches, instance of TemplateMonster\AjaxCatalog\Helper\Swatches\Data given, called in /home/username/public_html_dev/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /home/username/public_html_dev/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php on line 36' in /home/username/public_html_dev/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /home/username/public_html_dev/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php(36): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/home/username/...', 36, Array)
#1 /home/username/public_html_dev/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->__construct(Object(TemplateMonster\AjaxCatalog\Helper\Swatches\Data), Object(Magento\Eav\Model\Config), Object(Magento\Framework\App\Request\Http))
#2 /home/username/public_html_dev/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Smile\\Elasticsu...', Array)
#3 /home/username/public_html_dev/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Smile\\Elasticsu...')
#4 /home/username/public_html_dev/vendor/magento/framework/Interception/PluginList/PluginList.php(233): Magento\Framework\ObjectManager\ObjectManager->get('Smile\\Elasticsu...')
#5 /home/username/public_html_dev/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Catalog...', 'add_product_obj...')
#6 /home/username/public_html_dev/var/generation/Magento/Catalog/Block/Product/Widget/NewWidget/Interceptor.php(39): Magento\Catalog\Block\Product\Widget\NewWidget\Interceptor->___callPlugins('getImage', Array, Array)
#7 /home/username/public_html_dev/vendor/magento/module-catalog/view/frontend/templates/product/widget/new/content/new_grid.phtml(47): Magento\Catalog\Block\Product\Widget\NewWidget\Interceptor->getImage(Object(Magento\Catalog\Model\Product\Interceptor), 'new_products_co...')
#8 /home/username/public_html_dev/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/username/...')
#9 /home/username/public_html_dev/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\Widget\NewWidget\Interceptor), '/home/username/...', Array)
#10 /home/username/public_html_dev/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/username/...')
#11 /home/username/public_html_dev/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#12 /home/username/public_html_dev/vendor/magento/module-widget/Model/Template/Filter.php(117): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 /home/username/public_html_dev/vendor/magento/module-widget/Model/Template/Filter.php(128): Magento\Widget\Model\Template\Filter->generateWidget(Array)
#14 [internal function]: Magento\Widget\Model\Template\Filter->widgetDirective(Array)
#15 /home/username/public_html_dev/vendor/magento/framework/Filter/Template.php(141): call_user_func(Array, Array)
#16 /home/username/public_html_dev/vendor/magento/module-email/Model/Template/Filter.php(1011): Magento\Framework\Filter\Template->filter('<p><em><a href=...')
#17 /home/username/public_html_dev/vendor/magento/module-cms/Block/Page.php(157): Magento\Email\Model\Template\Filter->filter('<p><em><a href=...')
#18 /home/username/public_html_dev/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Cms\Block\Page->_toHtml()
#19 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('cms_page')
#21 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('cms_page')
#22 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('cms_page')
#23 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#24 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('content')
#25 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('content')
#26 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#27 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('main')
#28 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('main')
#29 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#30 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#31 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('columns')
#32 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#33 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#34 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('main.content')
#35 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#36 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#37 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper')
#38 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper.ou...')
#39 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper.ou...')
#40 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper.ou...')
#41 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#42 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('root')
#43 /home/username/public_html_dev/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout->renderElement('root')
#44 /home/username/public_html_dev/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#45 /home/username/public_html_dev/var/generation/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#46 /home/username/public_html_dev/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#47 /home/username/public_html_dev/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#48 /home/username/public_html_dev/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#49 /home/username/public_html_dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#50 /home/username/public_html_dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#51 /home/username/public_html_dev/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#52 /home/username/public_html_dev/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#53 /home/username/public_html_dev/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#54 /home/username/public_html_dev/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 /home/username/public_html_dev/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#56 /home/username/public_html_dev/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#57 /home/username/public_html_dev/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#58 /home/username/public_html_dev/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#59 /home/username/public_html_dev/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#60 {main} [] []
```

**Comment by nikonratm** [comment]
Seems like a fix for this is to change line 36 of /vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php from:
`\Smile\ElasticsuiteSwatches\Helper\Swatches $swatchesHelperData,`
to:
`\Magento\Swatches\Helper\Data $swatchesHelperData,`

Since both the TemplateMonster and ElasticSuite Swatch Helper classes extend the \Magento\Swatches\Helper\Data class the more general type in the constructor seems to work fine. Not sure if this will affect other users but hopefully can be integrated into an upcoming release?

**Comment by afoucret** [comment]
Hi @nikonratm,

We will have a look at this one very soon.
Can you tell us what versions of Magento and Elasticsuite are you using ?

The proposed solution does not seems accurate to me. It may lead to crashes when you select several values in a swatch attribute facets (eg. color). 
Magento sometimes does some breaking change in some constructor prototype even for minor release. It may be related.

**Comment by nikonratm** [comment]
Magento 2.1.3 and ES current version (core v0.0.1, swatches 0.0.1, catalog 1.2.0)

**Comment by romainruaud** [comment]
Hello @nikonratm , we are not supposed to give support for using custom themes with Elasticsuite. Since we do not have the issue on the Luma Default theme, this one is not an ElasticSuite issue.

But I can take a minute to reproduce this and to see if there is eventually a quickfix for it. Can you please indicate me how I can install the same theme as you so I'll be able to check ? 

Regards

**Comment by nikonratm** [comment]
Thanks for the reply. It's a commercial (i.e. not free) theme. If you are looking to help out I would be happy to give you access to the server, etc. (site is still under development).

Thanks either way!
