### ISSUE TITLE
"Only in stock products" condition stopped working!

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2897]
I have created a product carousel with the condition "Only in stock products"
This condition was working both in 2.4.5 and in 2.4.6. The only thing I remember changing is changing all the SKU of all the products (around 100 products). After that I cannot make the "Only in stock products" return any result. I have tried everything, cache clear, reindexing, disable & reenable the modules Smile_ElasticsuiteCatalogRule and Smile_ElasticsuiteVirtualCategory but nothing.
Side note here: Initially I had the same issue also with condition "Only discounted products" returning no products and disabling & enabling the above modules actually made this work again but no luck with condition "Only in stock products".

So I'm not sure if changing the SKUs was the cause of the problem. This is the last thing doing before breaking but to be honest doesn't make sense to be correlated.
Also, I want to report another probable issue:
In the following picture where the arrow shows the conditions, it doesn't show any number as it should
![image](https://user-images.githubusercontent.com/9040042/231091304-c1f9c8d8-3e2f-4efa-af97-f2ccac28a278.png)
There is an empty gap there, where it should show the number of found/filtered products.

### Preconditions

Magento Version : 2.4.6

ElasticSuite Version : 2.11.0

Environment : Developer

Third party modules : 

### Steps to reproduce

It's impossible to describe a method to reproduce as I'm not sure what caused the problem.

**Comment by Bashev** [comment]
If you add products they will be added, but counter is wrong, because of the error below.

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_stock.is_in_stock.value' in 'where clause', query was: SELECT DISTINCT  COUNT(DISTINCT e.entity_id) FROM `catalog_product_entity` AS `e`
 LEFT JOIN `catalog_product_super_link` AS `super_link_table` ON super_link_table.product_id = e.entity_id
 LEFT JOIN `catalog_product_link` AS `link_table` ON link_table.product_id = e.entity_id
 INNER JOIN `catalog_product_entity_int` AS `at_status_default` ON (`at_status_default`.`entity_id` = `e`.`entity_id`) AND (`at_status_default`.`attribute_id` = '97') AND `at_status_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '97') AND (`at_status`.`store_id` = 1) WHERE (((IFNULL(`at_stock`.`is_in_stock`.`value`, 0) = '1') )) AND (link_table.product_id IS NULL OR super_link_table.product_id IS NULL) AND (IF(at_status.value_id > 0, at_status.value, at_status_default.value) = '1')`

**Comment by cptX** [comment]
@Bashev just to make it clear for other readers here, your answer regards the counter that is not displayed. The real issue is why "Only in stock products" condition stopped working and doesn't show anymore on the widget. I save the content in page builder, save the page but still no products shown even if all are in stock! It was working a couple of days ago.
Is there some cache specific to this function that I should clear? The same happened also with condition "Only discounted products" but after disabling and enabling the modules started working again...

**Comment by vahonc** [comment]
Hello @cptX

I just checked on the fresh Magento (2.4.5 and 2.4.6) with the default sample data and ES (2.10.14 & 2.11.0) The "Only in stock products" condition is working as expected. There is no any magic (cache) here. Probably, it's a data issue or smth specific to your project/environment. 

Try to check your logs or enable Debug Mode for ElasticSute and provide us with your query.

 >In the following picture where the arrow shows the conditions, it never shows any number as it should, even if actually has found some products.

Yes, we are aware of this bug, but it's not a priority yet.

BR,
Vadym

**Comment by cptX** [comment]
Thanks @vahonc, the problem is I have no clue what happened and broke! I cannot correlate it with any action I did.
I have a test site with 2.4.5 where it is still working and another test site 2.4.6 where it was working and broke a couple of days ago. What I know I did is I changed the SKU to all products. But I changed the SKU to 1 product in 2.4.5 and there it didn't break anything...

Can you please give me a hint/guidance what to test, or at least which part of the elasticsuite code is responsible for this condition?

**Comment by vahonc** [comment]
@cptX,

Are you use the same version of ElasticSuite on both of your environments (2.4.5 and 2.4.6)?

Are you sure that everything reindex, all indexes are properly configured, cache cleared, etc?

How exactly you changed SKUs (manually or via some script)?

Did you try re-saved products after changing their SKUs?

Again, did you check Magento logs?

BR,
Vadym

**Comment by vahonc** [comment]
@cptX, it's very strange, because normally all should work as expected. Probably something wrong with the configuration of your store.

Have you tried to add some other conditions, just to test if this functionality is working?

Anyway, you could try start to debug it [here](https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-virtual-category/Plugin/Widget/ProductsListPlugin.php#L151). Maybe it will help you at least understand what's wrong there.

**Comment by cptX** [comment]
All the rest conditions work as expected. Only this one returns no results... Maybe uninstalling and reinstalling the module will help but I don't want to lose the settings...

**Comment by cptX** [comment]
Finally I managed to detect something in the logs:

[2023-04-12T19:33:27.960444+00:00] main.ERROR: Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/catalogAddToCart.js' [] []
[2023-04-12T19:33:27.961900+00:00] main.CRITICAL: Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/catalogAddToCart.js' [] []
[2023-04-12T19:33:31.180618+00:00] main.INFO: Broken reference: the 'notification.messages' tries to reorder itself towards 'user', but their parents are different: 'header.inner.right' and 'header' respectively. [] []
[2023-04-12T19:33:35.226737+00:00] main.CRITICAL: InvalidArgumentException: Class does not exist in /var/www/magento/vendor/magento/module-rule/Model/ConditionFactory.php:50
Stack trace:
#0 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Rule\Model\ConditionFactory->create()
#1 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Rule\Model\ConditionFactory\Interceptor->___callParent()
#2 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Rule\Model\ConditionFactory\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/magento/generated/code/Magento/Rule/Model/ConditionFactory/Interceptor.php(23): Magento\Rule\Model\ConditionFactory\Interceptor->___callPlugins()
#4 /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Combine.php(113): Magento\Rule\Model\ConditionFactory\Interceptor->create()
#5 /var/www/magento/vendor/magento/module-rule/Model/AbstractModel.php(320): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Combine->loadArray()
#6 /var/www/magento/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(101): Magento\Rule\Model\AbstractModel->loadPost()
#7 /var/www/magento/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(242): Magento\PageBuilder\Model\Catalog\ProductTotals->decodeConditions()
#8 /var/www/magento/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(150): Magento\PageBuilder\Model\Catalog\ProductTotals->applyConditionsToCollection()
#9 /var/www/magento/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(170): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductCollection()
#10 /var/www/magento/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(258): Magento\PageBuilder\Model\Catalog\ProductTotals->getEnabledCount()
#11 /var/www/magento/vendor/magento/module-page-builder/Controller/Adminhtml/Form/Element/ProductTotals.php(56): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductTotals()
#12 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals->execute()
#13 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#14 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/magento/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(23): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#16 /var/www/magento/vendor/magento/framework/App/Action/Action.php(111): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->execute()
#17 /var/www/magento/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#18 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#19 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#20 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#21 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#22 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/magento/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(32): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#24 /var/www/magento/vendor/magento/framework/App/FrontController.php(245): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->dispatch()
#25 /var/www/magento/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#26 /var/www/magento/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#27 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#28 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#29 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#30 /var/www/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#31 /var/www/magento/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#32 /var/www/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#33 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#34 /var/www/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#35 {main} [] []

**Comment by cptX** [comment]
Also strange is that in my composer I have:
        "smile/elasticsuite": "^2.10",

but in my admin page I see ElasticSuite Open Source ver. 2.11.0

**Comment by vahonc** [comment]
@cptX, does the error which you specified above still occur after all your steps?

Are you sure that ElasticSuite is selected as the default Search Engine in Magento BO:
`Stores -> Configuration -> Catalog -> Catalog -> Catalog Search -> Search Engine`?

Did you run these commands, after `composer require smile/elasticsuite ~2.11.0`

```
$ bin/magento setup:upgrade
$ bin/magento setup:di:compile
$ bin/magento indexer:reindex
$ bin/magento cache:clean
```

BR,
Vadym

**Comment by romainruaud** [comment]
Hi @cptX 

First of all : **don't use ^ in your composer requirements, never. Always use ~**.

And please ensure that you have : 

- on your Magento 2.4.5 : smile/elasticsuite ~2.10.0
- on your Magento 2.4.6 : smile/elasticsuite ~2.11.0

Regards

**Comment by cptX** [comment]
@vahonc yes Elasticsuite is the selected engine. Also, I ran all these commands, and I do this every time I change something (I have a script which runs all these commands...)

@romainruaud I don't have experience with composer. Do I need to modify composer.json manually everytime I need to make an update? I don't remember putting the ^ myself there...

I verify that in my 2.4.5 I have 2.10.13.3 and still works ok.
In my 2.4.6 I have 2.11.0. There it was working but after some, in my opinion irrelevant, changes the "Only in stock products" condition stopped working...

**Comment by cptX** [comment]
As I'm completely stuck on this and is the last thing needed to get fixed before publishing my site, I was thinking to downgrade the elasticsuite to 2.10.13 as in my 2.4.5. But I don't want to lose my settings or destroy data in my database. So can you please tell me if I can do this without implications? Will the data be preserved if I downgrade to 2.10.13?
Though I need 2.11 for the setting "Enable indexing discount on child products" which is not available in 2.10.

**Comment by romainruaud** [comment]
Hi,

the "Enable indexing discount on child products" is available in the latest 2.10 releases.

Please share the Elasticsearch query that is generated and triggered in the page where your widget resides.

Regards

**Comment by cptX** [comment]
> Hi,
> 
> the "Enable indexing discount on child products" is available in the latest 2.10 releases.
> 
> Please share the Elasticsearch query that is generated and triggered in the page where your widget resides.
> 
> Regards

How can I do this? Can you please guide me?

So if I downgrade to 2.10 will not have any issues?

**Comment by romainruaud** [comment]
You can enable the "debug mode" of Elasticsuite in Store > Configuration > Elasticsuite > Base Settings > Debug Mode : yes.

It will then process queries in the system.log file.

You can share the query that happens on the page containing your widget.

Regards

**Comment by cptX** [comment]
I cannot find any SQL query. 
I only see these:
`[2023-04-14T09:48:54.840343+00:00] main.WARNING: Deprecation ["299 Elasticsearch-7.17.9-ef48222227ee6b9e70e502f0f0daa52435ee634d \"Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.\""] []
[2023-04-14T09:48:54.842420+00:00] main.INFO: Request Success: {"method":"HEAD","uri":"http://localhost:9200/electrons_el_catalog_product","port":"9200","headers":{"Host":["localhost"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.17.1 (Linux 5.15.0-67-generic; PHP 8.1.16)"],"x-elastic-client-meta":["es=7.17.1,php=8.1.16,t=7.17.1,a=0,cu=7.81.0"]},"HTTP code":200,"duration":0.001574} []
[2023-04-14T09:48:54.844060+00:00] main.INFO: curl -XHEAD 'http://localhost:9200/electrons_el_catalog_product?pretty=true' [] []
`

**Comment by romainruaud** [comment]
you should see another query with a body (a big JSON body).

Maybe clear your cache before refreshing the page.

**Comment by cptX** [comment]
Maybe you mean this:

[2023-04-14T09:48:54.884275+00:00] main.INFO: curl -XPOST 'http://localhost:9200/electrons_el_catalog_product/_search?pretty=true' -d '{"size":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"terms":{"stock.is_in_stock":[true],"boost":1}}],"must_not":[],"should":[],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":10000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":10000,"order":{"_count":"desc"}}}},"track_total_hits":true}' [] []
[2023-04-14T09:48:54.890956+00:00] main.WARNING: Deprecation ["299 Elasticsearch-7.17.9-ef48222227ee6b9e70e502f0f0daa52435ee634d \"Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.\""] []
[2023-04-14T09:48:54.893051+00:00] main.INFO: Request Success: {"method":"POST","uri":"http://localhost:9200/electrons_el_catalog_product/_search","port":"9200","headers":{"Host":["localhost"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.17.1 (Linux 5.15.0-67-generic; PHP 8.1.16)"],"x-elastic-client-meta":["es=7.17.1,php=8.1.16,t=7.17.1,a=0,cu=7.81.0"]},"HTTP code":200,"duration":0.001828} []
[2023-04-14T09:48:54.894870+00:00] main.INFO: curl -XPOST 'http://localhost:9200/electrons_el_catalog_product/_search?pretty=true' -d '{"size":"20","sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"terms":{"stock.is_in_stock":[true],"boost":1}}],"must_not":[],"should":[],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":10000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":10000,"order":{"_count":"desc"}}}},"track_total_hits":0}' [] []

**Comment by cptX** [comment]
What command does a full reindex? The only command I know and use is bin/magento indexer:reindex

**Comment by romainruaud** [comment]
Yep, that's this one. clean cache and then do a full reindex.
