### ISSUE TITLE
"Only in stock products" condition shows also out-of-stock products

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2914]
In a carousel I want to filter products regarding their stock status. The "Only in stock products" condition continues to show also out-of-stock products.

### Preconditions
Magento CE 2.4.5
Elasticsuite 2.10.13.3

2 store views (greek and english)

Environment : Developer

Third party modules :
No third party modules installed

### Steps to reproduce

1. create some products
2.  set a product out-of-stock
3. create a carousel with the condition "Only in stock products"
4. carousel will show all products including the out-of-stock product

### Expected result
1. Condition "Only in stock products" should filter out all out-of-stock products

### Actual result
This condition actually does nothing. It's like not existing. It shows all products independently of their stock status.
![image](https://user-images.githubusercontent.com/9040042/233164376-e35980a9-f378-45f2-8927-702e316c4352.png)

![image](https://user-images.githubusercontent.com/9040042/233164502-96876081-20ed-4204-93e2-28d3acdd62e4.png)

I have checked the corresponding elasticsearch mapping and index and the info about the stock exists.

In the logs I see this 

`
[2023-04-19T18:16:16.212756+00:00] main.CRITICAL: InvalidArgumentException: Class does not exist in /var/www/electrons_test_03/vendor/magento/module-rule/Model/ConditionFactory.php:50
Stack trace:
#0 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Rule\Model\ConditionFactory->create()
#1 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Rule\Model\ConditionFactory\Interceptor->___callParent()
#2 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Rule\Model\ConditionFactory\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/electrons_test_03/generated/code/Magento/Rule/Model/ConditionFactory/Interceptor.php(23): Magento\Rule\Model\ConditionFactory\Interceptor->___callPlugins()
#4 /var/www/electrons_test_03/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Combine.php(113): Magento\Rule\Model\ConditionFactory\Interceptor->create()
#5 /var/www/electrons_test_03/vendor/magento/module-rule/Model/AbstractModel.php(320): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Combine->loadArray()
#6 /var/www/electrons_test_03/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(101): Magento\Rule\Model\AbstractModel->loadPost()
#7 /var/www/electrons_test_03/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(242): Magento\PageBuilder\Model\Catalog\ProductTotals->decodeConditions()
#8 /var/www/electrons_test_03/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(150): Magento\PageBuilder\Model\Catalog\ProductTotals->applyConditionsToCollection()
#9 /var/www/electrons_test_03/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(196): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductCollection()
#10 /var/www/electrons_test_03/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(260): Magento\PageBuilder\Model\Catalog\ProductTotals->getNotVisibleCount()
#11 /var/www/electrons_test_03/vendor/magento/module-page-builder/Controller/Adminhtml/Form/Element/ProductTotals.php(56): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductTotals()
#12 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(58): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals->execute()
#13 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#14 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/electrons_test_03/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(23): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#16 /var/www/electrons_test_03/vendor/magento/framework/App/Action/Action.php(111): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->execute()
#17 /var/www/electrons_test_03/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#18 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#19 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#20 /var/www/electrons_test_03/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#21 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#22 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/electrons_test_03/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(32): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#24 /var/www/electrons_test_03/vendor/magento/framework/App/FrontController.php(245): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->dispatch()
#25 /var/www/electrons_test_03/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#26 /var/www/electrons_test_03/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#27 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#28 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#29 /var/www/electrons_test_03/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#30 /var/www/electrons_test_03/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#31 /var/www/electrons_test_03/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#32 /var/www/electrons_test_03/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#33 /var/www/electrons_test_03/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#34 {main} [] []
`

**Comment by cptX** [comment]
With the help of @Bashev we found that the issue regarding the "Only in stock products" condition not working was not related to the error in the logs.
The problem was that I had copied some databases to make some test instances and in the copied databases in Views > inventory_stock_1 there were references to the original database and not the current... This was confusing the system thinging some products were in stock instead of out of stock...

Regarding the error in the logs is a separate issue and will be reported in another bug report.
