### ISSUE TITLE
TypeError: B2B Quick order suggest request 

### ISSUE THREAD

**Issue by vimart-smile** [Smile-SA/elasticsuite#2916]
### Preconditions
**Php version:**
```
PHP 8.1.14 (cli) (built: Jan  6 2023 00:57:24) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
```
**MySql version:**
```
mysql  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
**Elasticsearch info:**
```
{
  "name" : "83ab9b2a858f",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "nZSj7UO4Sf-41Kk5uj0yaA",
  "version" : {
    "number" : "7.17.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "de7261de50d90919ae53b0eff9413fd7e5307301",
    "build_date" : "2022-03-28T15:12:21.446567561Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Magento Version :** `EE v2.4.6`
**ElasticSuite Version :** `v2.11`
**Environment :** `Developer`

**Third party modules :**
```
    "require": {
        "akeneo/magento2-connector-enterprise": "^103.4",
        "amasty/mega-menu": "^2.4",
        "cart2quote/module-not2order": "^2.1",
        "cart2quote/module-quotation-encoded": "^4.3",
        "cweagans/composer-patches": "^1.7",
        "magento/composer-dependency-version-audit-plugin": "~0.1",
        "magento/composer-root-update-plugin": "~2.0",
        "magento/extension-b2b": "^1.3",
        "magento/product-enterprise-edition": "2.4.6",
        "mageplaza/magento-2-french-language-pack": "^1.0",
        "markshust/magento2-module-disabletwofactorauth": "^2.0",
        "smile/elasticsuite": "~2.11.0",
        "smile/module-cron": "^5.0",
        "smile/module-custom-entity": "^1.3",
        "smile/module-custom-entity-product-link": "^1.3",
        "smile/module-elasticsuite-quick-order": "^2.11",
        "smile/module-elasticsuite-shared-catalog": "~2.11",
        "smile/module-patch": "^1.0",
        "smile/module-reconfigure": "^5.0"
    }
```

### Steps to reproduce

1. Go to https://{{your_domain}}/quickorder/ (if 404 page, activate B2B Quick order feature in your BO)
2. Open `Networck` for your browser
3. Fiel filter by next value `quickorder/ajax_product/suggest`
4. Type the name for the existing product in the field `Enter SKU or search by Product Name`
5. Check API call for the filtered link with TypeError

### Expected result
1. Go to https://{{your_domain}}/quickorder/
2. Type the name for the existing product in the field `Enter SKU or search by Product Name`
3. Select from the drop-down list the needed product

### Actual result
1. Go to https://{{your_domain}}/quickorder/
2. Type the name for the existing product in the field `Enter SKU or search by Product Name`
3. Got error message: `The SKU was not found in the catalog. Product names must be typed manually.`

**TypeError from API call:**
**Url:** `https://{{your_domain}}/quickorder/ajax_product/suggest/?q={{prduct_name}}&_={{timestamp_value}}`
```
TypeError: Smile\ElasticsuiteCore\Model\Search\RequestBuilder::getRequest(): Argument #1 ($searchCriteria) must be of type Smile\ElasticsuiteCore\Api\Search\SearchCriteriaInterface, Magento\Framework\Api\Search\SearchCriteria given, called in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search.php on line 67 and defined in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search/RequestBuilder.php:96
Stack trace:
#0 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search.php(67): Smile\ElasticsuiteCore\Model\Search\RequestBuilder->getRequest(Object(Magento\Framework\Api\Search\SearchCriteria))
#1 /var/www/html/vendor/magento/module-quick-order/Model/FulltextSearch.php(96): Smile\ElasticsuiteCore\Model\Search->search(Object(Magento\Framework\Api\Search\SearchCriteria))
#2 /var/www/html/vendor/magento/module-quick-order/Model/Product/Suggest/DataProvider.php(66): Magento\QuickOrder\Model\FulltextSearch->search('{{prduct_name}}', 0)
#3 /var/www/html/vendor/magento/module-quick-order/Controller/Ajax/Product/Suggest.php(55): Magento\QuickOrder\Model\Product\Suggest\DataProvider->getItems('{{prduct_name}}')
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\QuickOrder\Controller\Ajax\Product\Suggest->execute()
#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->___callParent('execute', Array)
#6 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/html/generated/code/Magento/QuickOrder/Controller/Ajax/Product/Suggest/Interceptor.php(23): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->___callPlugins('execute', Array, Array)
#8 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->execute()
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->___callParent('dispatch', Array)
#11 /var/www/html/vendor/magento/module-company/Plugin/Framework/App/Action/AbstractActionPlugin.php(65): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Company\Plugin\Framework\App\Action\AbstractActionPlugin->aroundDispatch(Object(Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/generated/code/Magento/QuickOrder/Controller/Ajax/Product/Suggest/Interceptor.php(32): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->___callPlugins('dispatch', Array, Array)
#15 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor), Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\QuickOrder\Controller\Ajax\Product\Suggest\Interceptor))
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#20 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#26 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#28 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#29 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

```

**Comment by vahonc** [comment]
Duplicate of #2895
