### ISSUE TITLE
It seems like there is a conflict with a third-party module.

### ISSUE THREAD

**Issue by hgati** [Smile-SA/elasticsuite#2956]
### Preconditions
Magento Version : 2.4.6

ElasticSuite Version : 2.11.0

Environment : developer mode

Third party modules : 
Amasty_Base
Amasty_PreOrderAnalytic
Amasty_PreOrderMixedCart
Amasty_PreOrderPro
Amasty_PreOrderRelease
Amasty_Preorder
Amasty_ShippingTableRates
AvS_ScopeHint
Nwdthemes_Base
Faonni_SmartCategory
Faonni_SmartCategoryConfigurable
Faonni_SmartCategoryKit
Genaker_Opcache
Magefan_AdminUserGuide
Magefan_Community
Magefan_Blog
Magefan_BlogGraphQl
Magefan_WysiwygAdvanced
MagestyApps_WebImages
Olegnax_Athlete2
Nwdthemes_Revslider
Olegnax_Core
Olegnax_Athlete2Slideshow
Olegnax_BannerSlider
Olegnax_BrandSlider
Olegnax_Carousel
Olegnax_LayeredNavigation
Olegnax_GoogleMap
Olegnax_HotSpotQuickview
Olegnax_InfiniteScroll
Olegnax_InstagramMin
Olegnax_MegaMenu
Olegnax_NewsletterPopupBasic
Olegnax_ProductLabel
Olegnax_ProductReviewsSummary
Olegnax_ProductSlider
Olegnax_Quickview
Rakeshmagento_Autosku
Temando_ShippingRemover
Webkul_PurchaseManagement

### Steps to reproduce

1. composer require smile/elasticsuite ~2.11.0
2. bin/magento setup:upgrade
3. bin/magento setup:di:compile
4. bin/magento setup:static-content:deploy -f --theme=Magento/backend --theme=Olegnax/athlete2 en_US
5. bin/magento cache:flush
6. Go to the frontend and Click the menu on top.
7. "An error has happened during application run. See exception log for details."

### Expected result
The screen should be displayed properly.

### Actual result
var/log/exception.log
```
[2023-05-27T04:37:41.945254+00:00] main.CRITICAL: Error: Call to undefined method Olegnax\LayeredNavigation\Model\ResourceModel\Fulltext\Collection\Interceptor::addSortFilterParameters() in /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:87
Stack trace:
#0 /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php(67): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->setSortParams()
#1 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(121): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->beforePrepareProductCollection()
#2 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\Layer\Category\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/magento/generated/code/Magento/Catalog/Model/Layer/Category/Interceptor.php(23): Magento\Catalog\Model\Layer\Category\Interceptor->___callPlugins()
#4 /var/www/magento/vendor/magento/module-catalog/Model/Layer.php(147): Magento\Catalog\Model\Layer\Category\Interceptor->prepareProductCollection()
#5 /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php(110): Magento\Catalog\Model\Layer->getProductCollection()
#6 /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(129): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->applyCategoryFilterToCollection()
#7 /var/www/magento/vendor/magento/module-layered-navigation/Block/Navigation.php(70): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->apply()
#8 /var/www/magento/vendor/magento/framework/View/Element/AbstractBlock.php(272): Magento\LayeredNavigation\Block\Navigation->_prepareLayout()
#9 /var/www/magento/vendor/magento/framework/View/Layout/Generator/Block.php(149): Magento\Framework\View\Element\AbstractBlock->setLayout()
#10 /var/www/magento/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\Block->process()
#11 /var/www/magento/vendor/magento/framework/View/Layout.php(365): Magento\Framework\View\Layout\GeneratorPool->process()
#12 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->generateElements()
#13 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#14 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(32): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#16 /var/www/magento/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#17 /var/www/magento/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#18 /var/www/magento/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#19 /var/www/magento/vendor/magento/framework/View/Page/Config.php(227): Magento\Framework\View\Layout\Builder->build()
#20 /var/www/magento/vendor/magento/framework/View/Page/Config.php(591): Magento\Framework\View\Page\Config->build()
#21 /var/www/magento/vendor/magento/framework/View/Page/Config.php(549): Magento\Framework\View\Page\Config->getElementAttribute()
#22 /var/www/magento/vendor/magento/module-catalog/Controller/Category/View.php(246): Magento\Framework\View\Page\Config->addBodyClass()
#23 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Category\View->execute()
#24 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent()
#25 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/magento/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(23): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins()
#27 /var/www/magento/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Category\View\Interceptor->execute()
#28 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#29 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent()
#30 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#31 /var/www/magento/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(32): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins()
#32 /var/www/magento/vendor/magento/framework/App/FrontController.php(245): Magento\Catalog\Controller\Category\View\Interceptor->dispatch()
#33 /var/www/magento/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#34 /var/www/magento/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
#35 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#36 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#37 /var/www/magento/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#38 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#39 /var/www/magento/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#40 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#41 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#42 /var/www/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#43 /var/www/magento/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#44 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#45 /var/www/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#46 {main} {"exception":"[object] (Error(code: 0): Call to undefined method Olegnax\\LayeredNavigation\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor::addSortFilterParameters() at /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:87)"} []
[2023-05-27T04:47:02.978096+00:00] main.CRITICAL: Error: Call to undefined method Olegnax\LayeredNavigation\Model\ResourceModel\Fulltext\Collection\Interceptor::addSortFilterParameters() in /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:87
Stack trace:
#0 /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php(67): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->setSortParams()
#1 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(121): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->beforePrepareProductCollection()
#2 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\Layer\Category\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/magento/generated/code/Magento/Catalog/Model/Layer/Category/Interceptor.php(23): Magento\Catalog\Model\Layer\Category\Interceptor->___callPlugins()
#4 /var/www/magento/vendor/magento/module-catalog/Model/Layer.php(147): Magento\Catalog\Model\Layer\Category\Interceptor->prepareProductCollection()
#5 /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php(110): Magento\Catalog\Model\Layer->getProductCollection()
#6 /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(129): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->applyCategoryFilterToCollection()
#7 /var/www/magento/vendor/magento/module-layered-navigation/Block/Navigation.php(70): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->apply()
#8 /var/www/magento/vendor/magento/framework/View/Element/AbstractBlock.php(272): Magento\LayeredNavigation\Block\Navigation->_prepareLayout()
#9 /var/www/magento/vendor/magento/framework/View/Layout/Generator/Block.php(149): Magento\Framework\View\Element\AbstractBlock->setLayout()
#10 /var/www/magento/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\Block->process()
#11 /var/www/magento/vendor/magento/framework/View/Layout.php(365): Magento\Framework\View\Layout\GeneratorPool->process()
#12 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->generateElements()
#13 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#14 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(32): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#16 /var/www/magento/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#17 /var/www/magento/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#18 /var/www/magento/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#19 /var/www/magento/vendor/magento/framework/View/Page/Config.php(227): Magento\Framework\View\Layout\Builder->build()
#20 /var/www/magento/vendor/magento/framework/View/Page/Config.php(591): Magento\Framework\View\Page\Config->build()
#21 /var/www/magento/vendor/magento/framework/View/Page/Config.php(549): Magento\Framework\View\Page\Config->getElementAttribute()
#22 /var/www/magento/vendor/magento/module-catalog/Controller/Category/View.php(246): Magento\Framework\View\Page\Config->addBodyClass()
#23 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Category\View->execute()
#24 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent()
#25 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/magento/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(23): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins()
#27 /var/www/magento/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Category\View\Interceptor->execute()
#28 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#29 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent()
#30 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()
#31 /var/www/magento/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(32): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins()
#32 /var/www/magento/vendor/magento/framework/App/FrontController.php(245): Magento\Catalog\Controller\Category\View\Interceptor->dispatch()
#33 /var/www/magento/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#34 /var/www/magento/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
#35 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#36 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#37 /var/www/magento/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#38 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#39 /var/www/magento/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#40 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#41 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#42 /var/www/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#43 /var/www/magento/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#44 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#45 /var/www/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#46 {main} {"exception":"[object] (Error(code: 0): Call to undefined method Olegnax\\LayeredNavigation\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor::addSortFilterParameters() at /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:87)"} []
```
It seems like Magefan's Conflict Detector has detected module conflicts.
![Module Conflicts](https://i.ibb.co/1LnFBfM/image.png)

**Comment by vahonc** [comment]
Hello @hgati,

It's unlikely that our module and another one working on the same area (layered navigation) will function correctly.

So you'll have to make a choice between these two modules or resolve the conflicts by yourself (by coding).

I close since compatibility with third-party modules is out of the scope of our Open Source support policy provided here, there is not much we can do for your issue. 

BR,
Vadym

**Comment by agelospanagiotakis** [comment]
did you manage to solve this issue ?
 i have the same issue

**Comment by hgati** [comment]
> did you manage to solve this issue ? i have the same issue

No, I couldn't resolve it, so I removed the module and am not using it.
