### ISSUE TITLE
Magento 2.4.7 Call to undefined method Smile\ElasticsuiteCore\Search\Request\Query\Filtered::getReferenceType()

### ISSUE THREAD

**Issue by coresh** [Smile-SA/elasticsuite#3253]
### Preconditions

Magento Version : 2.4.7

ElasticSuite Version : 2.11.6

Environment : Developer

Environment:
```
uname -a
Linux v6.8.4-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr  4 20:40:57 UTC 2024 x86_64 GNU/Linux

php --version
PHP 8.2.17 (cli) (built: Mar 16 2024 01:56:04) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.17, Copyright (c), by Zend Technologies
```

Smile Environment:

```
smile/elasticsuite                       2.11.6
smile/module-custom-entity               1.3.15
smile/module-custom-entity-product-link  1.4.4
smile/module-elasticsuite-cms-search     2.2.8
smile/module-elasticsuite-quick-order    2.11.1
smile/module-elasticsuite-rating         2.3.2
smile/module-elasticsuite-shared-catalog 2.11.0
smile/module-elasticsuite-targetrule     1.4.1
smile/module-scoped-eav                  1.3.9
```

Third party modules : none

### Steps to reproduce
1. Checking Default Magento Cron jobs

### Expected result
1. Success Cron jobs

### Actual result

```
==> ./var/log/cron.log <==
[2024-04-12T19:20:03.214860+00:00] report.ERROR: Cron Job elasticsuite_index_log_event has an error: Call to undefined method Smile\ElasticsuiteCore\Search\Request\Query\Filtered::getReferenceType(). Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":130023424,"emalloc_start":59530680} [] []
[2024-04-12T19:20:03.215492+00:00] report.CRITICAL: Error: Call to undefined method Smile\ElasticsuiteCore\Search\Request\Query\Filtered::getReferenceType() in vendor/magento/module-elasticsearch/ElasticAdapter/SearchAdapter/Mapper.php:197
Stack trace:
#0 vendor/magento/module-elasticsearch/ElasticAdapter/SearchAdapter/Mapper.php(116): Magento\Elasticsearch\ElasticAdapter\SearchAdapter\Mapper->processFilterQuery(Object(Smile\ElasticsuiteCore\Search\Request\Query\Filtered), Array, 'must')
#1 vendor/magento/module-elasticsearch/ElasticAdapter/SearchAdapter/Mapper.php(72): Magento\Elasticsearch\ElasticAdapter\SearchAdapter\Mapper->processQuery(Object(Smile\ElasticsuiteCore\Search\Request\Query\Filtered), Array, 'must')
#2 vendor/magento/module-open-search/SearchAdapter/Mapper.php(38): Magento\Elasticsearch\ElasticAdapter\SearchAdapter\Mapper->buildQuery(Object(Smile\ElasticsuiteCore\Search\Request))
#3 vendor/magento/module-open-search/SearchAdapter/Adapter.php(107): Magento\OpenSearch\SearchAdapter\Mapper->buildQuery(Object(Smile\ElasticsuiteCore\Search\Request))
#4 vendor/magento/module-search/Model/SearchEngine.php(42): Magento\OpenSearch\SearchAdapter\Adapter->query(Object(Smile\ElasticsuiteCore\Search\Request))
#5 vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/ResourceModel/SessionIndex.php(73): Magento\Search\Model\SearchEngine->search(Object(Smile\ElasticsuiteCore\Search\Request))
#6 vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/SessionIndex.php(79): Smile\ElasticsuiteTracker\Model\ResourceModel\SessionIndex->getSessionData(61, Array)
#7 vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Cron/IndexLogEvent.php(83): Smile\ElasticsuiteTracker\Model\SessionIndex->indexEvents(Array)
#8 [internal function]: Smile\ElasticsuiteTracker\Cron\IndexLogEvent->execute(Object(Magento\Cron\Model\Schedule\Interceptor))
#9 vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(381): call_user_func_array(Array, Array)
#10 vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(904): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob(1712949600, 1712949602, Array, Object(Magento\Cron\Model\Schedule\Interceptor), 'default')
#11 vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(865): Magento\Cron\Observer\ProcessCronQueueObserver->tryRunJob(1712949600, 1712949602, Array, Object(Magento\Cron\Model\Schedule\Interceptor), 'default')
#12 vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(297): Magento\Cron\Observer\ProcessCronQueueObserver->processPendingJobs('default', Array, 1712949602)
#13 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Cron\Observer\ProcessCronQueueObserver->execute(Object(Magento\Framework\Event\Observer))
#14 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->___callParent('execute', Array)
#15 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\Event\Observer))
#16 generated/code/Magento/Cron/Observer/ProcessCronQueueObserver/Interceptor.php(23): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->___callPlugins('execute', Array, Array)
#17 vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor->execute(Object(Magento\Framework\Event\Observer))
#18 vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Cron\Observer\ProcessCronQueueObserver\Interceptor), Object(Magento\Framework\Event\Observer))
#19 vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#20 generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(105): Magento\Staging\Model\Event\Manager->dispatch('default', Array)
#21 vendor/magento/framework/App/Cron.php(86): Magento\Staging\Model\Event\Manager\Proxy->dispatch('default')
#22 vendor/magento/module-cron/Console/Command/CronCommand.php(140): Magento\Framework\App\Cron->launch()
#23 vendor/symfony/console/Command/Command.php(326): Magento\Cron\Console\Command\CronCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Cron\Console\Command\CronCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 bin/magento(23): Symfony\Component\Console\Application->run()
#29 {main}

```

Thank you

**Comment by coresh** [comment]
The issue: closed.

The reason:

Detected: issue affected by reset the config value of the "catalog/search/engine" to "opensearch"

Thank you
