### ISSUE TITLE
Bulk index operation failed 172 times

### ISSUE THREAD

**Issue by adamj88** [Smile-SA/elasticsuite#422]
Environment:

Magento 2.1.6 CE
Smile/ElasticSuite 2.3.5

Receiving the following error with ElasticSearch:

```
Bulk index operation failed 172 times in index magento_default_catalog_product_20170512_101302 for type product Error (mapper_parsing_exception) : failed to parse [collections] Failed doc ids sample : 18405, 18510, 18511, 18512, 18513, 18514, 18515, 18516, 18551, 18552
```
Further details in the elasticsearch log:

```
[2017-05-12 13:30:22,539][DEBUG][action.bulk              ] [Death-Stalker] [magento_wholesale_catalog_product_20170512_120229][0] failed to execute bulk item (index) index {[magento_wholesale_catalog_product][product][18934], source[{"entity_id":"18934","attribute_set_id":"22","type_id":"configurable","sku":"MST2948 Charcoal","has_options":"1","required_options":"1","created_at":"2017-05-10 03:17:12","updated_at":"2017-05-11 13:52:16","visibility":"4","price":[{"price":"29.9000","original_price":"29.9000","is_discount":false,"customer_group_id":"0"},{"price":"29.9000","original_price":"29.9000","is_discount":false,"customer_group_id":"1"},{"price":"29.9000","original_price":"29.9000","is_discount":false,"customer_group_id":"2"},{"price":"29.9000","original_price":"29.9000","is_discount":false,"customer_group_id":"3"},{"price":"29.9000","original_price":"29.9000","is_discount":false,"customer_group_id":"4"},{"price":"29.9000","original_price":"29.9000","is_discount":false,"customer_group_id":"5"}],"category":[{"category_id":2,"is_parent":true},{"category_id":27,"is_parent":true,"name":"Men"},{"category_id":48,"is_parent":true,"name":"Men's Tops"},{"category_id":253,"is_parent":true,"name":"Men's T-Shirts"},{"category_id":254,"is_parent":true,"name":"No Ordinary Cotton"},{"category_id":380,"is_parent":true,"name":"New Season Stripes"},{"category_id":409,"is_parent":true,"name":"All Men's"},{"category_id":421,"is_parent":true,"name":"Menswear 2017"}],"collections":["Vegan"],"name":["Vincent Organic Cotton Jersey Top"],"image":["\/2\/1\/2165813057-mst2948-vincent-organic-cotton-top-charcoal-front_1.jpg"],"style":["MST2948"],"product_fabric":[26],"option_text_product_fabric":["Organic Cotton"],"season":[651],"option_text_season":["March '17"],"children_ids":[14413,14414,14415,14416,14417,14419],"children_attributes":["option_text_collections","product_size","option_text_product_size"],"configurable_attributes":[null,"product_size"],"option_text_collections":["Vegan"],"product_size":[211,212,213,214,210],"option_text_product_size":["M","L","XL","XXL","S"],"stock":{"is_in_stock":true,"qty":0}}]}
MapperParsingException[failed to parse [collections]]; nested: NumberFormatException[For input string: "Vegan"];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:329)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:311)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:438)
	at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:426)
	at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:381)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:256)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:124)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:584)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:563)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:657)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:287)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "Vegan"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.intValue(AbstractXContentParser.java:127)
	at org.elasticsearch.index.mapper.core.IntegerFieldMapper.innerParseCreateField(IntegerFieldMapper.java:293)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:241)
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:321)
	... 24 more
```

Appears to be having trouble inserting the `collections` attribute into ElasticSearch, this attribute is set up as follows:

```
attribute_id: 214
entity_type_id: 4
attribute_code: 'collections'
attribute_model: NULL
backend_model: 'Magento\\Eav\\Model\\Entity\\Attribute\\Backend\\ArrayBackend'
backend_type: 'text'
backend_table: NULL
frontend_model: NULL
frontend_input: 'multiselect'
frontend_label: 'Collection'
frontend_class: NULL
source_model: NULL
is_required: 0
is_user_defined: 1
default_value: '649'
is_unique: 0
note: NULL
```

In other multiselect a attributes we're seeing both a numeric value and a text value passed, in the above error an example would be: `"season":[651],"option_text_season":["March '17"]`

**Comment by afoucret** [comment]
Hi @adamj88

I suspect the attribute has been created in a way that is not standard.

By the way in sample data multi-select attributes look like :

```
attribute_id: 195
entity_type_id: 4
attribute_code: climate
attribute_model: NULL
backend_model: Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend
backend_type: varchar
backend_table: NULL
frontend_model: NULL
frontend_input: multiselect
frontend_label: Climate
frontend_class: NULL
source_model: NULL
is_required: 0
is_user_defined: 1
default_value: 
is_unique: 0
note: NULL
```

I think the backend_model should be varchar in order to have a proper option ids storage in Magento eav tables.

**Comment by adamj88** [comment]
Hi @afoucret

The attribute was created from a Magento 1 migration which looks to have not updated the `backend_type`. 

Changing the `backend_type` to varchar has resolved this.

Thanks for the help!
