### ISSUE TITLE
Initial Indexing error - at setup

### ISSUE THREAD

**Issue by Fuzzzzy** [Smile-SA/elasticsuite#655]
I've set up elasticsearch extension but it's not working. It throws error at the indexing. I've followed the setup guides and configured Elastic Search accordingly. 

I've did a test with another extension (https://www.wyomind.com/elastic-search-magento.html) and it's working fine with that. Can you please help out with this?  

### Preconditions

Magento Version : 1.9.3.7

ElasticSuite Version : 1.3.0

Environment :Production, but we have a Staging environment as well

Third party modules :

![image](https://user-images.githubusercontent.com/15350181/33833657-fde3f6cc-de88-11e7-83a5-496f829704a8.png)

### Steps to reproduce

1. Initial index of Elastic Search in Magento admin throws the following error

### Expected result

1. Normal reindex and a working product search.

### Actual result

1. [Screenshot]
![image](https://user-images.githubusercontent.com/15350181/33833781-752be672-de89-11e7-9c6a-e2f217cb8a74.png)

Exception Log

2017-12-11T13:23:34+00:00 DEBUG (7): Exception message: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Can't update non dynamic settings[[index.merge.policy.merge_factor]] for open indices [[magento112-20171211-132302]]"}],"type":"illegal_argument_exception","reason":"Can't update non dynamic settings[[index.merge.policy.merge_factor]] for open indices [[magento112-20171211-132302]]"},"status":400}
Trace: #0 /home/######/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"number_of_rep...')
#1 /home/######/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"number_of_rep...')
#2 /home/######/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('PUT', '/magento112-201...', Array, '{"number_of_rep...')
#3 /home/######/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('PUT', '/magento112-201...', Array, Array)
#4 /home/######/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(246): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /home/######/public_html/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(483): Elasticsearch\Namespaces\IndicesNamespace->putSettings(Array)
#6 /home/######/public_html/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(197): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->installNewIndex()
#7 /home/######/public_html/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#8 /home/######/public_html/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#9 /home/######/public_html/app/code/core/Mage/Index/controllers/Adminhtml/ProcessController.php(127): Mage_Index_Model_Process->reindexEverything()
#10 /home/######/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Index_Adminhtml_ProcessController->reindexProcessAction()
#11 /home/######/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('reindexProcess')
#12 /home/######/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /home/######/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#14 /home/######/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /home/######/public_html/index.php(86): Mage::run('', 'store')
#16 {main}

es-queries.log

`2017-12-11T11:58:05+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"fields":["entity_id"],"track_scores":true,"sort":[{"position":{"order":"asc","missing":9223372036854775806,"ignore_unmapped":true,"nested_path":"category_position","nested_filter":{"term":{"category_id":"12"}}}},{"_score":"desc"}],"from":64,"size":32}}
2017-12-11T11:58:13+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"fields":["entity_id"],"track_scores":true,"sort":[{"position":{"order":"asc","missing":9223372036854775806,"ignore_unmapped":true,"nested_path":"category_position","nested_filter":{"term":{"category_id":"210"}}}},{"_score":"desc"}],"from":0,"size":32}}
2017-12-11T11:58:29+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"fquery":{"query":{"query_string":{"query":"(categories:17) OR (show_in_categories:17)"}},"_cache":true}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"facets":{"attribute_set_id":{"terms":{"size":8,"order":"count","field":"attribute_set_id"},"facet_filter":{"bool":{"must":[{"terms":{"options_greutate_ro.untouched":["25L"]}},{"range":{"price_0_1":{"gte":"220"}}}]}}}},"filter":{"bool":{"must":[{"terms":{"options_greutate_ro.untouched":["25L"]}},{"range":{"price_0_1":{"gte":"220"}}}]}},"from":0,"size":0}}
2017-12-11T11:59:58+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"fields":["entity_id"],"track_scores":true,"sort":[{"position":{"order":"asc","missing":9223372036854775806,"ignore_unmapped":true,"nested_path":"category_position","nested_filter":{"term":{"category_id":"102"}}}},{"_score":"desc"}],"from":0,"size":32}}
2017-12-11T12:00:10+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"fields":["entity_id"],"track_scores":true,"sort":[{"position":{"order":"asc","missing":9223372036854775806,"ignore_unmapped":true,"nested_path":"category_position","nested_filter":{"term":{"category_id":"281"}}}},{"_score":"desc"}],"from":0,"size":32}}
2017-12-11T12:00:17+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"fquery":{"query":{"query_string":{"query":"(categories:17) OR (show_in_categories:17)"}},"_cache":true}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"facets":{"attribute_set_id":{"terms":{"size":8,"order":"count","field":"attribute_set_id"}}},"from":0,"size":0}}
2017-12-11T12:01:08+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"fields":["entity_id"],"track_scores":true,"sort":[{"position":{"order":"asc","missing":9223372036854775806,"ignore_unmapped":true,"nested_path":"category_position","nested_filter":{"term":{"category_id":"29"}}}},{"_score":"desc"}],"from":0,"size":32}}
2017-12-11T12:01:42+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"fields":["entity_id"],"track_scores":true,"sort":[{"position":{"order":"asc","missing":9223372036854775806,"ignore_unmapped":true,"nested_path":"category_position","nested_filter":{"term":{"category_id":"162"}}}},{"_score":"desc"}],"from":0,"size":32}}
2017-12-11T12:01:46+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"fields":["entity_id"],"track_scores":true,"sort":[{"position":{"order":"asc","missing":9223372036854775806,"ignore_unmapped":true,"nested_path":"category_position","nested_filter":{"term":{"category_id":"75"}}}},{"_score":"desc"}],"from":0,"size":32}}
2017-12-11T12:02:16+00:00 DEBUG (7): {"index":"magento","type":"product","body":{"query":{"filtered":{"query":{"bool":{"must":[{"match_all":[]}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[2,4]}},{"terms":{"status":[1]}},{"fquery":{"query":{"query_string":{"query":"(categories:17) OR (show_in_categories:17)"}},"_cache":true}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"facets":{"attribute_set_id":{"terms":{"size":8,"order":"count","field":"attribute_set_id"},"facet_filter":{"bool":{"must":[{"terms":{"options_aroma_ro.untouched":["Ananas"]}},{"terms":{"options_manufacturer_ro.untouched":["SipCarp"]}}]}}}},"filter":{"bool":{"must":[{"terms":{"options_aroma_ro.untouched":["Ananas"]}},{"terms":{"options_manufacturer_ro.untouched":["SipCarp"]}}]}},"from":0,"size":0}}`

**Comment by romainruaud** [comment]
Hello,

please move your issue to the Magento1 module repository here : https://github.com/Smile-SA/smile-magento-elasticsearch

Also, please do not forget to indicate which version of Elasticsearch you are using. I guess you are probably using a non-supported version of Elasticsearch.

I close the issue here since this is not the proper repository.

**Comment by Fuzzzzy** [comment]
Oh sorry, thanks.
