### ISSUE TITLE
Disk Space reached 100% used and now sharding.

### ISSUE THREAD

**Issue by crantron** [Smile-SA/elasticsuite#697]
Disk Space reached 100% used and now sharding.

### Preconditions
Centos 7.1 
Mysql 5.6.35
PHP 7.2
Apache 2.4

Magento Version : 2.2.2 CE

ElasticSuite Version : 2.4.6

Environment : Developer

### Actual result
![screen shot 2018-01-18 at 10 08 56 am](https://user-images.githubusercontent.com/3859969/35113808-a1e897c0-fc37-11e7-9404-601f9f0bd023.png)
*elasticsearch.log*
```
[2018-01-18 17:34:09,140][INFO ][node                     ] [Alyosha Kravinoff] version[2.4.6], pid[2104], build[5376dca/2017-07-18T12:17:44Z]
[2018-01-18 17:34:09,141][INFO ][node                     ] [Alyosha Kravinoff] initializing ...
[2018-01-18 17:34:10,075][INFO ][plugins                  ] [Alyosha Kravinoff] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2018-01-18 17:34:10,159][INFO ][env                      ] [Alyosha Kravinoff] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [29.1gb], net total_space [37.5gb], spins? [unknown], types [rootfs]
[2018-01-18 17:34:10,159][INFO ][env                      ] [Alyosha Kravinoff] heap size [999mb], compressed ordinary object pointers [true]
[2018-01-18 17:34:13,408][INFO ][node                     ] [Alyosha Kravinoff] initialized
[2018-01-18 17:34:13,408][INFO ][node                     ] [Alyosha Kravinoff] starting ...
[2018-01-18 17:34:13,552][INFO ][transport                ] [Alyosha Kravinoff] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-01-18 17:34:13,562][INFO ][discovery                ] [Alyosha Kravinoff] elasticsearch/tjuV0V_3SLqMgGw6ptUIqA
[2018-01-18 17:34:16,628][INFO ][cluster.service          ] [Alyosha Kravinoff] new_master {Alyosha Kravinoff}{tjuV0V_3SLqMgGw6ptUIqA}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2018-01-18 17:34:16,657][INFO ][http                     ] [Alyosha Kravinoff] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2018-01-18 17:34:16,657][INFO ][node                     ] [Alyosha Kravinoff] started
[2018-01-18 17:34:16,825][INFO ][gateway                  ] [Alyosha Kravinoff] recovered [7] indices into cluster_state
[2018-01-18 17:34:16,871][WARN ][indices.cluster          ] [Alyosha Kravinoff] [[magento2_default_catalog_category_20180117_231357][0]] marking and sending shard failed due to [failed to create index]
[magento2_default_catalog_category_20180117_231357] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown TokenFilter type [phonetic] for [phonetic]];
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:317)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:174)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:622)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Unknown TokenFilter type [phonetic] for [phonetic]
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:222)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:154)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)
        ... 9 more
[2018-01-18 17:34:16,874][WARN ][cluster.action.shard     ] [Alyosha Kravinoff] [magento2_default_catalog_category_20180117_231357][0] received shard failed for target shard [[magento2_default_catalog_category_20180117_231357][0], node[tjuV0V_3SLqMgGw6ptUIqA], [P], v[7], s[INITIALIZING], a[id=0h50KLiVTSKHpXl7tJ8CXw], unassigned_info[[reason=CLUSTER_RECOVERED], at[2018-01-18T17:34:16.672Z]]], indexUUID [e-RJq-BAQdOb1yKn6oBl4g], message [failed to create index], failure [IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown TokenFilter type [phonetic] for [phonetic]]; ]
[magento2_default_catalog_category_20180117_231357] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown TokenFilter type [phonetic] for [phonetic]];
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:317)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:174)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:622)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Unknown TokenFilter type [phonetic] for [phonetic]
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:222)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:154)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)
        ... 9 more
[2018-01-18 17:34:16,874][WARN ][cluster.action.shard     ] [Alyosha Kravinoff] [magento2_default_catalog_category_20180117_231357][0] received shard failed for target shard [[magento2_default_catalog_category_20180117_231357][0], node[tjuV0V_3SLqMgGw6ptUIqA], [P], v[7], s[INITIALIZING], a[id=0h50KLiVTSKHpXl7tJ8CXw], unassigned_info[[reason=CLUSTER_RECOVERED], at[2018-01-18T17:34:16.672Z]]], indexUUID [e-RJq-BAQdOb1yKn6oBl4g], message [failed to create index], failure [IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown TokenFilter type [phonetic] for [phonetic]]; ]
[magento2_default_catalog_category_20180117_231357] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown TokenFilter type [phonetic] for [phonetic]];
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:362)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:317)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:174)
        at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:622)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Unknown TokenFilter type [phonetic] for [phonetic]
        at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:222)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:154)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)
```

I fixed the disk space issue, but just need to resolve the loop of processes.

**Comment by afoucret** [comment]
The interesting part of the stacktrace is here : 

```
[2018-01-18 17:34:16,874][WARN ][cluster.action.shard     ] [Alyosha Kravinoff] [magento2_default_catalog_category_20180117_231357][0] received shard failed for target shard [[magento2_default_catalog_category_20180117_231357][0], node[tjuV0V_3SLqMgGw6ptUIqA], [P], v[7], s[INITIALIZING], a[id=0h50KLiVTSKHpXl7tJ8CXw], unassigned_info[[reason=CLUSTER_RECOVERED], at[2018-01-18T17:34:16.672Z]]], indexUUID [e-RJq-BAQdOb1yKn6oBl4g], message [failed to create index], failure [IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown TokenFilter type [phonetic] for [phonetic]]; ]
```

The `Unknown TokenFilter type [phonetic] for [phonetic]];` means that you don't have the plugin filter installed. If you have append some new nodes, you should install the phonetic plugin on each node (there is no global command allowing to install the plugin cluster wide).

So you have to run the following command on each node :

```
bin/plugin install analysis-phonetic
bin/plugin install analysis-icu
```

Do not forget to restart the elasticsearch service and to reindex in Magento then.

More information are available here : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig

BR,

**Comment by crantron** [comment]
![screen shot 2018-01-24 at 11 21 50 am](https://user-images.githubusercontent.com/3859969/35352452-d3eec80a-00f8-11e8-9f78-e2747f396588.png)

**Comment by crantron** [comment]
its already installed, I have followed the installation directions exactly.

**Comment by southerncomputer** [comment]
you have to remove the old version after upgrading elasticsearch.

try remove analysis-phonetic then install analysis-phonetic and then service restart elasticsearch

**Comment by crantron** [comment]
I did this and still the problem persists
