### ISSUE TITLE
Timeout - Page load forever.

### ISSUE THREAD

**Issue by kauansoft** [Smile-SA/elasticsuite#739]
### Preconditions
Magento 2.2.2
Centos 7.4
WHM/cPanel (Last Version)
PHP-FPM OFF
ElasticSuite Last Version

A fresh installation of magento with last version of elasticsuite and i get 504 gateway timeout, page is loading forever and the css don't load, i give 777 to all to try resolve, but nothings happens.

Apache log:
```
[Fri Feb 09 15:32:39.720018 2018] [cgi:warn] [pid 707] [client 186.249.192.149:7501] AH01220: Timeout waiting for output from CGI script /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.mysite.com/
[Fri Feb 09 15:32:39.720063 2018] [cgi:error] [pid 707] [client 186.249.192.149:7501] Script timed out before returning headers: ea-php71, referer: https://www.mysite.com/
```
![image](https://user-images.githubusercontent.com/27354497/36042153-09fd836c-0db2-11e8-8658-74a4c1c9929e.png)

`curl localhost:9200`

Response: curl: (7) Failed connect to localhost:9200; Connection refused

---------------
Sometimes `curl localhost:9200` works...

---------------

Admin page is blank after login.
Log apache:

```
[Fri Feb 09 16:12:04.179362 2018] [cgi:error] [pid 8581] [client 186.249.192.149:1246] AH01215: PHP Fatal error:  Uncaught Error: Call to a member function setActive() on boolean in /home/hortibras/public_html/vendor/magento/module-backend/Model/View/Result/Page.php:27: /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.hortibras.com/painel/admin/index/index/key/0f640726d1655ec51eb2332ec354b97ecd52031f12f473ca0a0a20bed16e8b5d/
[Fri Feb 09 16:12:04.179402 2018] [cgi:error] [pid 8581] [client 186.249.192.149:1246] AH01215: Stack trace:: /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.hortibras.com/painel/admin/index/index/key/0f640726d1655ec51eb2332ec354b97ecd52031f12f473ca0a0a20bed16e8b5d/
[Fri Feb 09 16:12:04.179470 2018] [cgi:error] [pid 8581] [client 186.249.192.149:1246] AH01215: #0 /home/hortibras/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu('Magento_Backend...'): /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.hortibras.com/painel/admin/index/index/key/0f640726d1655ec51eb2332ec354b97ecd52031f12f473ca0a0a20bed16e8b5d/
[Fri Feb 09 16:12:04.179553 2018] [cgi:error] [pid 8581] [client 186.249.192.149:1246] AH01215: #1 /home/hortibras/public_html/vendor/magento/module-backend/Controller/Adminhtml/Dashboard/Index.php(35): Magento\\Backend\\Model\\View\\Result\\Page\\Interceptor->setActiveMenu('Magento_Backend...'): /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.hortibras.com/painel/admin/index/index/key/0f640726d1655ec51eb2332ec354b97ecd52031f12f473ca0a0a20bed16e8b5d/
[Fri Feb 09 16:12:04.179636 2018] [cgi:error] [pid 8581] [client 186.249.192.149:1246] AH01215: #2 /home/hortibras/public_html/generated/code/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(24): Magento\\Backend\\Controller\\Adminhtml\\Dashboard\\Index->execute(): /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.hortibras.com/painel/admin/index/index/key/0f640726d1655ec51eb2332ec354b97ecd52031f12f473ca0a0a20bed16e8b5d/
[Fri Feb 09 16:12:04.179720 2018] [cgi:error] [pid 8581] [client 186.249.192.149:1246] AH01215: #3 /home/hortibras/public_html/vendor/magento/framework/App/Action/Action.php(107): Magento\\Backend\\Controller\\Adminhtml\\Dashboard\\Index\\Interceptor->execute(): /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.hortibras.com/painel/admin/index/index/key/0f640726d1655ec51eb2332ec354b97ecd52031f12f473ca0a0a20bed16e8b5d/
[Fri Feb 09 16:12:04.179819 2018] [cgi:error] [pid 8581] [client 186.249.192.149:1246] AH01215: #4 /home/hortibras/public_html/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatc in /home/hortibras/public_html/vendor/magento/module-backend/Model/View/Result/Page.php on line 27: /usr/local/cpanel/cgi-sys/ea-php71, referer: https://www.hortibras.com/painel/admin/index/index/key/0f640726d1655ec51eb2332ec354b97ecd52031f12f473ca0a0a20bed16e8b5d/

```

**Comment by kauansoft** [comment]
`curl localhost:9200`

Response: curl: (7) Failed connect to localhost:9200; Connection refused

**Comment by afoucret** [comment]
I fear, there is nothing we can do until you have a stable connection to the ElasticSearch server through curl.

Closed for not being related to ElasticSuite but to  your ElasticSearch install.

**Comment by kauansoft** [comment]
It was some incompatibilite with WHM/cPanel, i'm using Directadmin now and everything is fine.
