### ISSUE TITLE
Error happening in Categories Admin

### ISSUE THREAD

**Issue by ngandara-summa** [Smile-SA/elasticsuite#877]
We have a Magento 2.2 site, with Elastic Suite. Not sure why, but we have had this error a couple of times.

We don’t have a sistematic way to reproduce it. When the error starts happening, it happens all the time.

to explain it a bit better:  it happened once in our QA environment, and we are not sure why, but it “solved itself”. Now we are installing our website in the environment that will be production, and it is ocurring again.

What we can tell you are details that we see when the problem occurs. Hope this helps to understand it

Magento Version : 2.2.0 EE
ElasticSuite Version : 2.5
Environment : Production
Third party modules :nono

### Steps to reproduce
1 Go to Menu, catalog, categories.
2. We see a stuck page   ![1_catalog_errorsmile](https://user-images.githubusercontent.com/8005884/38879909-d1b785bc-423a-11e8-8aa7-868414949bb8.png)
3. Opening the browser inspector, we see the following errors: ![2_catalog_errorsmile](https://user-images.githubusercontent.com/8005884/38880009-0782a64a-423b-11e8-8a21-e81dcbdf339d.png)
4. Stack Trace:
Error message
Error: Uncaught exception 'Error' with message 'Call to a member function getCategorySearchQuery() on null' in /var/www/site/releases/vdevelop_103/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php:103

Sample stack trace
…/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/
Preview.php (73)
…csuite/src/module-elasticsuite-catalog/Model/ProductSorter/
AbstractPreview.php (140)
…csuite/src/module-elasticsuite-catalog/Model/ProductSorter/
AbstractPreview.php (150)
…csuite/src/module-elasticsuite-catalog/Model/ProductSorter/
AbstractPreview.php (83)
…lasticsuite-virtual-category/Controller/Adminhtml/Category/Virtual/
Preview.php (71)
…/www/site/releases/vdevelop_103/vendor/magento/framework/App/Action/
Action.php (107)
…ite/releases/vdevelop_103/vendor/magento/module-backend/App/
AbstractAction.php (229)
…te/releases/vdevelop_103/vendor/magento/framework/Interception/
Interceptor.php (58)
…te/releases/vdevelop_103/vendor/magento/framework/Interception/
Interceptor.php (138)
…develop_103/vendor/magento/module-backend/App/Action/Plugin/
Authentication.php (143)
…te/releases/vdevelop_103/vendor/magento/framework/Interception/
in Magento\Backend\App\Action\Plugin\Authentication::aroundDispatch called at /var/www/site/releases/vdevelop_103/vendor/magento/framework/Interception/Interceptor.php
Interceptor.php (135)
…te/releases/vdevelop_103/vendor/magento/framework/Interception/
Interceptor.php (153)
…eVirtualCategory/Controller/Adminhtml/Category/Virtual/Preview/
Interceptor.php (26)
…ww/site/releases/vdevelop_103/vendor/magento/framework/App/
FrontController.php (55)
…te/releases/vdevelop_103/vendor/magento/framework/Interception/
Interceptor.php (58)
…te/releases/vdevelop_103/vendor/magento/framework/Interception/
Interceptor.php (138)
…te/releases/vdevelop_103/vendor/magento/framework/Interception/
Interceptor.php (153)
…velop_103/generated/code/Magento/Framework/App/FrontController/
Interceptor.php (26)
…d at /var/www/site/releases/vdevelop_103/vendor/magento/framework/App/
Http.php (135)
…/var/www/site/releases/vdevelop_103/vendor/magento/framework/App/
Bootstrap.php (256)
…App\Bootstrap::run called at /var/www/site/releases/vdevelop_103/pub/
index.php (37)

**Comment by afoucret** [comment]
Hi @ngandara-summa,

Think your problem is a duplicate of #748, #787 and #836.

Can you confirm increasing max_input_vars solve it ?

**Comment by shrinet** [comment]
Hello,
  I am still getting this error, my environment is
Magento Version : 2.2.7 CE
ElasticSuite Version : 5.6.15
Environment : Production

Stack Trace:
`[06-Mar-2019 22:11:12 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getCategorySearchQuery() on null in /home/rfs/readyforshop.com/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php:105
Stack trace:
#0 /home/rfs/readyforshop.com/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(75): Smile\ElasticsuiteVirtualCategory\Model\Preview->getQueryFilter()
#1 /home/rfs/readyforshop.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ProductSorter/AbstractPreview.php(148): Smile\ElasticsuiteVirtualCategory\Model\Preview->prepareProductCollection(Object(Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor))
#2 /home/rfs/readyforshop.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ProductSorter/AbstractPreview.php(158): Smile\ElasticsuiteCatalog\Model\ProductSorter\AbstractPreview->getProductCollection()
#3 /home/rfs/readyforshop.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ProductSorter/ in /home/rfs/readyforshop.com/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php on line 105`

Please suggest

**Comment by ulftietze** [comment]
Can confirm.

**Comment by ulftietze** [comment]
Hey Guys,

debugged myself into this and found a possible bug/solution.
In my project i was extending the Magento\Catalog\Model\Category and replaced it with a <preference .../>

Removing this preference, clearing all caches and generated classes, this works like a charm ^^
